### ISSUE TITLE
Missing canonical and prev/next tags on shop subpages

### ISSUE THREAD

**Issue by monbauza** [Yoast/wpseo-woocommerce#100]
Canonical and prev/next tags disappear from shop page and subpages (i.e. /shop/page/2/) when WooCommerce SEO is activated.

WordPress 4.4.2
WooCommerce 2.5.5
Yoast SEO 3.1.1
WooCommerce SEO 3.1.1

**Comment by monbauza** [comment]
Please inform the customer of conversation # 103704 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 101812 when this conversation has been closed.

**Comment by jeffrhap** [comment]
Any progress on this? Reported this a month ago.

**Comment by jeffrhap** [comment]
A temporary piece of code maybe? I really need to fix this.

**Comment by jeffrhap** [comment]
Seems to be solved when the Woocommerce SEO plug-in is disabled!

**Comment by tacoverdo** [comment]
![view-source_clean_dev_shop_page_2](https://cloud.githubusercontent.com/assets/5147598/14814739/e72f06d4-0ba7-11e6-8a4e-9b01a79cbe59.png)
_WooCommerce SEO deactivated_

![view-source_clean_dev_shop_page_2](https://cloud.githubusercontent.com/assets/5147598/14814763/fd1741e6-0ba7-11e6-8bee-4af904192255.png)
_WooCommerce SEO active_

**Tested versions**
WordPress 4.5
Yoast SEO 3.2.3
WooCommerce SEO 3.2

**Comment by jdevalk** [comment]
For future reference, this is related to [#512 on Yoast SEO](https://github.com/Yoast/wordpress-seo/issues/512).
