### ISSUE TITLE
Add-on settings not linked under SEO adminbar

### ISSUE THREAD

**Issue by diedexx** [Yoast/wpseo-woocommerce#102]
Unlike Video SEO, wpseo-woo does not have an adminbar item linking to the settings pages.
![screen shot 2016-03-02 at 14 41 14](https://cloud.githubusercontent.com/assets/5352634/13462772/4b9adba6-e089-11e5-838f-a835e4fbec7c.png)
## Using

Yoast SEO 3.1
wpseo-woo 3.1

**Comment by moorscode** [comment]
This is present in the latest version.
