### ISSUE TITLE
Page analysis broken in combination with Yoast SEO 3.1+

### ISSUE THREAD

**Issue by omarreiss** [Yoast/wpseo-woocommerce#103]
Yoast WooCommerce SEO still depends on the StringHelper which has been removed in 3.1. Please come up with a fix.

We don't want to do another release of Yoast SEO, so I think it'd be best to duplicate the `stripAllTags` function as a private function used in the context of https://github.com/Yoast/wpseo-woocommerce/blob/trunk/js/yoastseo-woo-plugin.js

**Comment by atimmer** [comment]
Fixed in #104
