### ISSUE TITLE
remove add_submenu_page translations

### ISSUE THREAD

**Issue by diedexx** [Yoast/wpseo-woocommerce#115]
![untitled](https://cloud.githubusercontent.com/assets/5352634/14744058/435eee98-08a5-11e6-9d1f-4fb441ab8bb8.png)
Since wooCommerce SEO is a product name we don't want it to be translatable.

**Comment by moorscode** [comment]
According to the following line, these are not translatable at the moment:
https://github.com/Yoast/wpseo-woocommerce/blob/187817fde62d9533368934a787d24792e69059cc/wpseo-woocommerce.php#L523
