### ISSUE TITLE
Errors occur in content analysis with Yoast SEO 3.3

### ISSUE THREAD

**Issue by rensw90** [Yoast/wpseo-woocommerce#120]
Yoast WooCommerce plugin doesn't work.

1. Add a product
2. Edit the product
3. Navigate to the keyword tab in the meta box.

![edit_product_ _acc-subdomain_ _wordpress](https://cloud.githubusercontent.com/assets/7293908/15824937/f65b4224-2c01-11e6-9383-6c0fde95aac8.jpg)

Yoast SEO 3.3-beta3
Latest WooCommerce and Yoast WooCommerce plugin

**Comment by moorscode** [comment]
Related https://github.com/Yoast/wpseo-video/issues/260

**Comment by jcomack** [comment]
I recompiled YoastSEO.js for the plugin, which is now available on `trunk`.

Testing
First install a version based off of the `master` branch and follow the steps described by @rensw90.
Then, install a version based on the `trunk` branch and follow the same steps again. The error should no longer be there.

**Comment by atimmer** [comment]
Acceptance done 👍🏻
