### ISSUE TITLE
Product Categories do not display correct meta descriptions on Facebook

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-woocommerce#122]
Tested in Dev environment and the og:description is not being changed, unless WooCommerece SEO is deactivated

**Image One: Product Category Edit Screen  with lorem text**

![screen shot 2016-06-09 at 8 17 59 am](https://cloud.githubusercontent.com/assets/8238074/15929424/efd85656-2e1a-11e6-8594-c504c7f746ae.png)

**Image Two: Snippet Editor Screen showing Facebook descriptions**

![screen shot 2016-06-09 at 8 18 18 am](https://cloud.githubusercontent.com/assets/8238074/15929442/03e2f930-2e1b-11e6-91c2-a671e08a6fa9.png)

**Image Three: Sourcecode**

![meta desc](https://cloud.githubusercontent.com/assets/8238074/15929464/276ab258-2e1b-11e6-9ba2-0907e7de102e.jpg)

**Image Four: Deactivate Yoast WooCommerce SEO and the sourcecode came through** 

![fb desc](https://cloud.githubusercontent.com/assets/8238074/15929612/fd69e388-2e1b-11e6-9f77-77296bd66748.jpg)

**Tech Specs:**
WordPress: 4.5.2 (on a multisite)
Yoast Seo Premium: 3.2.5
Yoast WooCommerce SEO: 3.2
WooCommerce: 2.5.5
StoreFront Theme: 2.0.3

Note: Original issue was placed in wrong repository. You can view original issue here: https://github.com/Yoast/wordpress-seo/issues/4331

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 109060 when this conversation has been closed.

**Comment by benvaassen** [comment]
Email sent to the customer and asked for an update.

**Comment by thulshof** [comment]
Not able to reproduce and no response from customer (see # 168853 ). Closing this issue.
