### ISSUE TITLE
Add support for meta fields on the shop page

### ISSUE THREAD

**Issue by atimmer** [Yoast/wpseo-woocommerce#127]
Currently, when editing the shop page in the admin the values set for the meta tags are not reflected on the frontend. This has to do with the fact that the WooCommerce shop page isn't actually a page. It is the products post type archive.

This issue has been raised on the Yoast SEO repository but we decided to fix it in Yoast SEO: WooCommerce. See https://github.com/Yoast/wordpress-seo/issues/4362.

https://github.com/Yoast/wpseo-woocommerce/issues/119 might be related.

**Comment by TMGD43** [comment]
I'm curious to know, when or if there is an eta on when this issue will be resolved within Yoast SEO for WooCommerce?

Not having a meta description or thumbnail when sharing your store's front page is atrocious lol...

**Comment by monbauza** [comment]
Please inform the customer of conversation #  151396 when this conversation has been closed.

**Comment by EasyEl** [comment]
This issue still persists. As Woocommerce is now the number 1 shopping cart and part of Automattic this should be considered standard and not "one of many" plugins. Any idea when this will get resolved?

**Comment by monbauza** [comment]
Please inform the customer of conversation # 162661 when this conversation has been closed.

**Comment by suascat** [comment]
Please inform the customer of conversation # 213447 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 228890 when this conversation has been closed.

**Comment by YendiGB** [comment]
More than one year later... and STILL no resolution? Are you even taking this seriously?! This is a paid plugin... not being able to have this description in the MAIN store page is a deal breaker for me. I will not renew my subscription when it expires.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 243554 when this conversation has been closed.

**Comment by suascat** [comment]
Please inform the customer of conversation # 253923 when this conversation has been closed.

**Comment by suascat** [comment]
Please inform the customer of conversation # 268539 when this conversation has been closed.

**Comment by suascat** [comment]
Please inform the customer of conversation # 392284 when this conversation has been closed.

**Comment by moorscode** [comment]
This has been fixed in a recent version of Yoast SEO.
