### ISSUE TITLE
Incorrect Internal Links Settings Page

### ISSUE THREAD

**Issue by iamazik** [Yoast/wpseo-woocommerce#130]
### What did you expect to happen?

The internal links settings page would work.
### What happened instead?

The internal links settings page doesn't work and shows the following permission error even for the administrator:
`You do not have sufficient permissions to access this page.`
### Example Internal Links Settings Page

`http://example.com/wp-admin/admin.php?page=wpseo_internal-links`
### How can we reproduce this behavior?
1. Go to the WooCommerce SEO settings page
2. Click on the Internal links settings page from the Breadcrumbs section.
### Technical info
- WordPress version: 4.5.3
- Yoast SEO version: 3.4.2
- WooCommerce SEO: 3.4

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 141699 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 141605 when this conversation has been closed.

**Comment by georgippetrov** [comment]
Thank you for the quick response. I will wait and hope to hear from you soon. One more thing just appear. I don't see any options for the Twitter card in SEO for Woocommerce as you advertise on your website. Is that something on my side because I use the free version of Yoast SEO or just another bug.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 167852 when this conversation has been closed.

**Comment by Pcosta88** [comment]
![screen_shot_2017-04-04_at_3_46_48_pm](https://cloud.githubusercontent.com/assets/8238074/24675681/1a9d8630-194e-11e7-902e-f38303b43932.png)

![screen_shot_2017-04-04_at_3_46_41_pm](https://cloud.githubusercontent.com/assets/8238074/24675701/269886f6-194e-11e7-93aa-4ccde5ba23bc.png)

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 188831 when this conversation has been closed.

**Comment by strayangelfilms** [comment]
Hi there, is this being fixed?  This ticket is from August 2016!?!

**Comment by monbauza** [comment]
Please inform the customer of conversation # 190807 when this conversation has been closed.

**Comment by amboutwe** [comment]
Please inform the customer of conversation # 204735 when this conversation has been closed.

**Comment by strayangelfilms** [comment]
Please actually fix this issue.  Why does it take a year to fix a bug?

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 239737 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation #  257890 when this conversation has been closed.

**Comment by rumejan** [comment]
Please inform the customer of conversation # 282659 when this conversation has been closed.
