### ISSUE TITLE
[Feature Request] Add ability to locate products geographically and locally 

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-woocommerce#131]
We offer a Local SEO plugin which helps users/sites be found locally. If we can and it makes sense to take advantage of other schema, markup, JSON+LD etc, we should add onto the WooCommerce SEO to help products be found locally.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 144477 when this conversation has been closed.

**Comment by moorscode** [comment]
This is something that Local SEO already solves by adding the geographical information to your site.
