### ISSUE TITLE
Implement support of primary term for products/categories

### ISSUE THREAD

**Issue by Rarst** [Yoast/wpseo-woocommerce#135]
### What did you expect to happen?

For primary category feature to pick chosen product category in URL.

### What happened instead?

Native WP behavior apples, primary category is not used in URL.

### How can we reproduce this behavior?

See https://github.com/Yoast/wordpress-seo/issues/6013#issuecomment-259237263

### Technical info
* WordPress version: 4.6.1
* Yoast SEO version: 3.7.1

**Comment by moorscode** [comment]
Primary category is currently implemented for Products (or any other Custom Post Type).

**Comment by jmead** [comment]
Primary term is implemented however you cannot default it to a level. We have 100,000 products with 3 levels of cats, we want to default each products cats to use the first level as the primary cat.
