### ISSUE TITLE
No Extra Columns Appear in the All Product Page View

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-woocommerce#137]
### What did you expect to happen?
Extra Columns output by Yoast would appear
### What happened instead?
No columns (besides SEO and Readability) appear. 
### How can we reproduce this behavior?
**1.Make sure to UnClick on "Remove Yoast Columns" in SEO->WooCommerce SEO->Admin**

![screen shot 2016-12-28 at 9 08 26 am](https://cloud.githubusercontent.com/assets/8238074/21523542/37fe3188-ccdd-11e6-9218-3789e0342a8a.png)

**2.Ensure that Screen Options have everything enabled**

**3.See that no extra columns appear**

![1](https://cloud.githubusercontent.com/assets/8238074/21523563/60e9cbb6-ccdd-11e6-916d-19f75651497f.png)

**Tech Info**
* WordPress version: 4.7
* WooCommerce SEO version: 4.0
* Yoast SEO Prem: 4.0.2

**Comment by andizer** [comment]
The option is to disable the addition of Yoast SEO columns. These would be added besides the column that will be added by WooCommerce itself. By leave the checkbox unchecked all columns will be visible.  The Yoast SEO for WooCommerce won't add any columns. I think this issue can be closed.
