### ISSUE TITLE
[Feature Request] Provide markup for Price and Availablity to appear when a product is shared on Twitter

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-woocommerce#139]
Currently, the WooCommerce SEO plugin only has the ability to output Price and Availability for Pinterest. We should provide the right markup so that Price and Availability appear on Twitter

Note: Twitter has depreciated the product cards in favor of the summer card. You can see the recommended markup for Price and Availability to appear on Twitter here:  https://dev.twitter.com/cards/types/product

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 175462 when this conversation has been closed.

**Comment by thulshof** [comment]
Pinterest uses the [OpenGraph data](https://developers.pinterest.com/docs/rich-pins/products/?) to get the product prices and availability. Twitter doesn't pick up the OG price and availability, as you can see at the [Cards Markup Tag Reference](https://dev.twitter.com/cards/markup). This means there are no possibilities for us to add this feature. Writing an appropriate meta description would be the best (and only?) alternative.
