### ISSUE TITLE
Fatal error: Class 'yoast_i18n' not found

### ISSUE THREAD

**Issue by iamazik** [Yoast/wpseo-woocommerce#142]
### What did you expect to happen?
No fatal error.

### What happened instead?
The following fatal error occurs while navigating to the WooCommerece settings page.
`PHP Fatal error: Class 'yoast_i18n' not found in /nas/content/live/clevelandwcr/wp-content/plugins/wpseo-woocommerce/wpseo-woocommerce.php on line 722, referer: https://www.clevelan…admin.php?page=wpseo_redirects`

### Technical info
* WordPress version: 4.7.2
* Yoast SEO version: 4.2.1
* WooCommerce SEO version: 4.2

**Comment by iamazik** [comment]
Please inform the customer of conversation # 177525 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 176895 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 177564 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 177520 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 177541 when this conversation has been closed.

**Comment by atimmer** [comment]
We released 4.2.1 to fix this issue.
