### ISSUE TITLE
Unit Tests with PHP 7.1

### ISSUE THREAD

**Issue by Ramoonus** [Yoast/wpseo-woocommerce#145]
### What did you expect to happen?
Automated Unit testing (on travis ci) currently does not happen with PHP 7.1

### How can we reproduce this behavior?

Can you provide a link to a page which shows this issue?

### Technical info
* WordPress version:
* Yoast SEO version:

**Comment by CarolineGeven** [comment]
Closing as unit tests currently run with PHP 7 and PHP 7.2.
