### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'Yoast_Product_WPSEO_WooCommerce'

### ISSUE THREAD

**Issue by AiratHalitov** [Yoast/wpseo-woocommerce#146]
### What did you expect to happen?
I try to activate this plugin.
https://github.com/Yoast/wpseo-woocommerce/releases/tag/4.5

### What happened instead?

```
[03-Apr-2017 18:31:29 UTC] PHP Fatal error:  Uncaught Error: Class 'Yoast_Product_WPSEO_WooCommerce' not found in /site_path/wp-content/plugins/wpseo-woocommerce/wpseo-woocommerce.php:915
Stack trace:
#0 /site_path/wp-includes/class-wp-hook.php(298): yoast_woocommerce_seo_activate_license('')
#1 /site_path/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array)
#2 /site_path/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /site_path/wp-admin/plugins.php(166): do_action('activate_wpseo-...')
#4 {main}
  thrown in /site_path/wp-content/plugins/wpseo-woocommerce/wpseo-woocommerce.php on line 915
```

### Technical info
* WordPress version: 4.7.3
* Yoast SEO version: 4.5
* BuddyPress version: 2.8.2
* WooCommerce version: 2.6.14
* PHP version: 7.1.3-3+deb.sury.org~xenial+1

**Comment by CarolineGeven** [comment]
Thanks for reporting this issue. Is this happening with Yoast SEO (premium) or if you try to activate the plugin on its own?

**Comment by AiratHalitov** [comment]
It's not premium.

**Comment by CarolineGeven** [comment]
What I mean, does this happen with the Yoast SEO Free or premium plugin active or does it happen if you do not have Yoast SEO Free or premium active? Yoast SEO WooCommerce only works if you have free or premium active as well. I'm trying to determine when this exactly happens.

**Comment by AiratHalitov** [comment]
Yoast SEO Free is active when I try to activate wpseo-woocommerce plugin.

**Comment by AiratHalitov** [comment]
I desided that i'm not gonna use this plugin (wpseo-woocommerce)
You can close that issue.
