### ISSUE TITLE
Does the plugin still exclude and include stuff in the XML sitemap? 

### ISSUE THREAD

**Issue by benvaassen** [Yoast/wpseo-woocommerce#147]
### What did you expect to happen?
To see changes in the sitemap when I activate Yoast SEO for WooCommerce. We advertise with: 
> It’ll exclude unnecessary things from the sitemap and makes sure the things that do need to get in the sitemap will be in there.

But when I only have Yoast SEO (Premium) active, I don't see any difference with Yoast SEO for WooCommerce. There are functions that add stuff to the sitemap, for example `add_product_images_to_xml_sitemap` (see: https://github.com/Yoast/wpseo-woocommerce/blob/trunk/wpseo-woocommerce.php#L240)

### What happened instead?
I don't see any change happen in my sitemap when I activate Yoast SEO for WooCommerce. Nothing seems to be removed or added. 

### How can we reproduce this behavior?
- Install WooCommerce with demo products
- Activate Yoast SEO (Premium)
- Check the sitemap (ensure everything is enabled)
- Activate Yoast SEO for WooCommerce
- Check the sitemap again, no changes are seen.

### Can you provide a link to a page which shows this issue?
Check all the sitemap pages, in my case: 
- sitemap_index.xml
- post-sitemap.xml
- page-sitemap.xml
- attachment-sitemap.xml
- product-sitemap.xml
- category-sitemap.xml
- post_tag-sitemap.xml
- product_cat-sitemap.xml
- author-sitemap.xml
![xml_sitemap](https://cloud.githubusercontent.com/assets/11910661/24798891/c80cb1dc-1b98-11e7-801b-46343bd7cef5.png)

### Technical info
* WordPress version: 4.7.3
* Yoast SEO (Premium) version: 4.5
* Yoast SEO for WooCommerce: 4.5

**Comment by Annelieke** [comment]
@PatrickYoast Can you check this out? I notice that the product sitemap etc. is included, but the way I read it that's already included if you install WooCommerce. So what does our WooCommerce plugin actually add? What's the SEO benefit?

**Comment by PatrickYoast** [comment]
I think you might be confusing the `product image` and the `product image gallery`. The Function is referring to is there to add `product image gallery` images to the product sitemap. Which in my testing it still does.

## Without Yoast WooCommerce:
![8ef51d44-3af1-11e7-9a23-5b9d6b3f1f4d](https://cloud.githubusercontent.com/assets/14159618/26146813/c68bfc00-3af1-11e7-86c9-bcab51831e4e.png)

![xml_sitemap](https://cloud.githubusercontent.com/assets/14159618/26146773/ab3e6a1e-3af1-11e7-92cc-35d221bbfff3.png)

## With Yoast WooCommerce active
![xml_sitemap](https://cloud.githubusercontent.com/assets/14159618/26146927/25bf3480-3af2-11e7-882a-0438dfb1f1f8.png)

**Comment by thulshof** [comment]
Ok, I'll close this issue because this has been clarified.

**Comment by Pcosta88** [comment]
related: https://github.com/Yoast/wpseo-woocommerce/issues/165
