### ISSUE TITLE
[Feature Request] Provided Google structured data for product star ratings

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-woocommerce#148]
We should include markup for Google Product reviews. Google explains more about the markup here: https://developers.google.com/search/docs/data-types/products

Currently, if a user wants to add product star ratings they will need to review the plugin repository for one that can best match their needs: https://wordpress.org/plugins/

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 150219 when this conversation has been closed.

**Comment by jdevalk** [comment]
Woo does this themselves, we shouldn't.
