### ISSUE TITLE
"Internal Links settings page" link needs to be updated part II

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-woocommerce#149]
Clicking on the Internal Links Settings page in SEO->WooCommerce does not work

![screen_shot_2017-04-14_at_8_23_14_am](https://cloud.githubusercontent.com/assets/8238074/25043172/f4ffceec-20eb-11e7-976c-072edc70f9c5.png)

It takes you to a page:  http://patsmultisite.com/wp-admin/admin.php?page=wpseo_internal-links  with the error message of "Sorry, you are not allowed to access this page."

![screen shot 2017-04-14 at 8 23 23 am](https://cloud.githubusercontent.com/assets/8238074/25043188/0a6beee6-20ec-11e7-8d03-8f838ff58659.png)

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 190807 when this conversation has been closed.

**Comment by strayangelfilms** [comment]
Cross referencing this ticket with https://github.com/Yoast/wordpress-seo/issues/7002 as if this internal links settings issue is fixed perhaps the option to hide Woo's /Shop page in the product sitemap can be added to the Woo SEO plugin as well.

**Comment by thulshof** [comment]
Duplicate https://github.com/Yoast/wpseo-woocommerce/issues/130 - closing this issue.
