### ISSUE TITLE
Replace WooBreadcrumbs Option Not Working

### ISSUE THREAD

**Issue by amboutwe** [Yoast/wpseo-woocommerce#150]
### What did you expect to happen?
WooBreadcrumbs would be replaced with Yoast breadcrumbs

### What happened instead?
WooBreadcrumbs remained.

### How can we reproduce this behavior?

1. Activate Yoast SEO, WooCommerce, and Yoast SEO: WooCommerce
2. Enable Yoast Breadcrumbs ( Admin > SEO > Advanced > Breadcrumbs ).
3. Set Separator to » (WooCom default is / so it's easier if this is not the same)
4. Enable Override option ( Admin > SEO > WooCommerce SEO )
5. View a product. The breadcrumbs do not reflect Yoast breadcrumb settings.

### Technical info
* WordPress version: 4.7.4
* Yoast SEO version: 4.6
* Yoast SEO: WooCommerce version: 4.6
* WooCommerce version: 3.0.5

### Workaround
Add code to functions.php
https://gist.github.com/amboutwe/ab1652f1f7d73f8cf19d80ebe245fc0a

### Screenshots
![selection_015](https://cloud.githubusercontent.com/assets/8060612/25550746/05a865a8-2c39-11e7-9bdb-2502ea95a8aa.png)
![selection_016](https://cloud.githubusercontent.com/assets/8060612/25550748/0868319c-2c39-11e7-9ce5-a4d4fe4934cd.png)
![selection_017](https://cloud.githubusercontent.com/assets/8060612/25550743/ff7d19ee-2c38-11e7-947e-28e5a89b0d7a.png)

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 292487 when this conversation has been closed.

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 370458 when this conversation has been closed.

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 409408  when this conversation has been closed.

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 408629  when this conversation has been closed.

**Comment by suascat** [comment]
Please inform the customer of conversation # 413447 when this conversation has been closed.

**Comment by benvaassen** [comment]
The context of this issue seems to be related: https://github.com/Yoast/wordpress-seo/issues/10314
If possible, keep this in mind.

**Comment by laurasacco** [comment]
Please, inform the customer of conversation # 443080 when this conversation has been closed.
