### ISSUE TITLE
Facebook override og:image don't working as YOAST SEO main plugin

### ISSUE THREAD

**Issue by r1si** [Yoast/wpseo-woocommerce#151]
Hi all !
In my site I have installed:
* Yoast SEO: WooCommerce 4.7
* Yoast SEO Premium 4.7

If I go to a normal page (it uses  Yoast SEO Premium) and I setup YOAST with facebook override image: 
in my tag head I have *correctly* only one tag "og:image"

`<meta property="og:image" content="https://example.com/URL_TO_OVERRIDEN_IMG" />`

if I go on woocommerce products (it uses  Yoast SEO WooCommerce) and I setup YOAST with facebook override image: 
in my tag head I have *wrongly* more tag "og:image" and the override one to last position:

`<meta property="og:image" content="https://example.com/URL_TO_GALLERY_1_IMG" />`
`<meta property="og:image" content="https://example.com/URL_TO_GALLERY_2_IMG" />`
`<meta property="og:image" content="https://example.com/URL_TO_FEATURE_IMG" />`
`<meta property="og:image" content="https://example.com/URL_TO_OVERRIDEN_IMG" />`

Any idea about it?

**Comment by thulshof** [comment]
Unfortunately, this is not a bug, but a support request. We use GitHub exclusively for (well-documented) bug reports, so we cannot help you here.

To receive free support for WordPress SEO we have the following channels:
* [Yoast Knowledge base](http://kb.yoast.com)
* [Support forums](https://wordpress.org/support/plugin/wordpress-seo) on WordPress.org

Or if you want personal support via email, you can purchase [WordPress SEO Premium](https://yoast.com/wordpress/plugins/seo-premium/).

Thanks for your understanding.

**Comment by r1si** [comment]
Sorry but this is a evident BUG not a configuration mistake!
I have already open a support ticket, but the support say me only: "Please update the plugin" (I have already update to latest version but did't work)
Have you understand my problem?
