### ISSUE TITLE
Does the plugin exclude items from the sitemap still?

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-woocommerce#165]
**On this page here: https://yoast.com/wordpress/plugins/yoast-woocommerce-seo/ we state**

> It’ll exclude unnecessary things from the sitemap and makes sure the things that do need to get in the sitemap will be in there.

**I understand from this issue: https://github.com/Yoast/wpseo-woocommerce/issues/147 that it includes the WooCommerce Galleries.** 

**However, what does the WooCommerce SEO _exclude_ from the sitemaps?**

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 211210 when this conversation has been closed.

**Comment by thulshof** [comment]
There is some code that modifies the content of the sitemap. The first one obviously excludes things, not completely sure about the second: 

- Make sure product attribute taxonomies are not included in the XML sitemap. 
https://github.com/Yoast/wpseo-woocommerce/blob/trunk/wpseo-woocommerce.php#L497

- Filters the archive link on the product sitemap -  https://github.com/Yoast/wpseo-woocommerce/blob/trunk/wpseo-woocommerce.php#L742
