### ISSUE TITLE
Retailer Open Graph properties for products

### ISSUE THREAD

**Issue by galbaras** [Yoast/wpseo-woocommerce#166]
### What did you expect to happen?

There are several Open Graph fields used to describe the retailer of a product, which may be of benefit. I would expect them to be covered by the plugin. Given that the company details and its FB page details can be available from Yoast SEO, these could even be fallbacks to specific settings used by Yoast WooCommerce SEO.

### What happened instead?

There is no place for retailer attributes in the plugin's admin and they do not appear in the OG tags for products.

### How can we reproduce this behavior?

Create a product page and view it.

### Can you provide a link to a page which shows this issue?

https://www.sentani.com.au/product/fire-rain-asymmetric-maxi/

### Technical info
* WordPress version: 4.8.1
* Yoast SEO version: 5.1

**Comment by Pcosta88** [comment]
related: https://github.com/Yoast/wpseo-woocommerce/issues/128

**Comment by moorscode** [comment]
Closing this in favor of #128
