### ISSUE TITLE
[Feature Request] - Provide the Ability to Add Product Specific Brand

### ISSUE THREAD

**Issue by iamazik** [Yoast/wpseo-woocommerce#168]
### What did you expect to happen?
An option to select brand from the individual product page instead of selecting the brand for all products from the WooCommerce settings.

In some cases, user may need to select a different brand certain products instead of what the user specified from the WooCommerce settings.

### What happened instead?
Currently, we can only select brands for all products from the WooCommerce SEO plugin settings.

According to the user:

> To make appear in microformat in the search engines, I do not find where it is because I can only select either product labels, product categories or attributes but have nothing to do with the brand. Is it possible at a place to choose product by product what should be displayed as microformat in the search engines? Where it is only possible to choose for all of all products.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 216324 when this conversation has been closed.

**Comment by Djennez** [comment]
That's something WooCommerce seems to do https://woocommerce.com/products/brands/
