### ISSUE TITLE
Facebook image not used when Image Gallery is set

### ISSUE THREAD

**Issue by monbauza** [Yoast/wpseo-woocommerce#169]
### What did you expect to happen?
When a Facebook Image is defined in the social tab of the Yoast metabox, it would show up when sharing the product on Facebook.

### What happened instead?
The images in the product gallery appear first.
Related https://github.com/Yoast/wpseo-woocommerce/issues/54

### How can we reproduce this behavior?

1. Install and activate Yoast SEO, WooCommerce SEO and WooCommerce
2. Go to the edit screen of a product
3. Provide several images in the product gallery
4. Go to the social tab of the Yoast metabox and define an image for Facebook
5. Check the source code of the product page and notice the Facebook image set in the Yoast metabox appears last (see image below). This image also appears last in the list when the product is shared on Facebook.

![image](https://user-images.githubusercontent.com/9658774/29602919-607c884c-87e2-11e7-9589-4a8b9a3ca967.png)

![image](https://user-images.githubusercontent.com/9658774/29603028-d17b41e6-87e2-11e7-9bc4-15712c7abe09.png)

### Technical info
* WordPress version: 4.8.1
* Yoast SEO version: 5.3.1
* WooCommerce SEO version: 5.3
* WooCommerce version: 3.1.2

**Comment by monbauza** [comment]
Please inform the customer of conversation # 217043 when this conversation has been closed.

**Comment by amboutwe** [comment]
Please inform the customer of conversation # 213447 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 222394 when this conversation has been closed.

**Comment by YendiGB** [comment]
Any news on this? This is the main reason I acquired the Woocommerce Premium Yoast bundle and the suscription time is ticking... still I cannot use the share snippets.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 253077 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation #  254124 when this conversation has been closed.

**Comment by monbauza** [comment]
_Workaround_: add the Facebook Image also to the product gallery and drag it to the first position.

**Comment by whatevs-already** [comment]
Like previous commenter @YendiGB the main reason I acquired Premium Yoast was for the Facebook share. When will this major issue be fixed please? Also re: the "workaround" reported abit – it was me found this workaround however it's not ideal. If you add the FB image to the product gallery and drag to first position then use Facebook's debug tool here -- https://developers.facebook.com/tools/debug/sharing/ -- to re-scrape the page link, the correct FB image will appear in your FB share. However this workaround creates issues with other areas in woocommerce that are also taking their image from first position in the product gallery, such as the shopping cart. Now my customers see the FB image in their shopping cart. Not ideal :-)

**Comment by whatevs-already** [comment]
@benvaassen thanks for the update it's appreciated, is it possible to estimate a timeline on the issue being fixed?

**Comment by moorscode** [comment]
This change requires some adjustment in Yoast SEO.
There are two approaches to this solution, as far as I see it:

1. Priority based approach - We implement a way to provide priority when adding an image to the OG image stack
2. Additional hook approach - We implement an additional hook, below the default images.

The second approach seems the easiest and most efficient.

**Comment by whatevs-already** [comment]
Hi, my apologies I'm not a developer I'm the graphic designer who reported the issue – I received an email that this issue is closed, does this mean it's fixed? Cheers.

**Comment by benvaassen** [comment]
Hi @whatevs-already 
The issue has been fixed in our development branch. You can expect the fix to be included in the next release of Yoast SEO WooCommerce 5.9.

**Comment by whatevs-already** [comment]
Thank you so much for jumping on this, very appreciated. My website https://insultingpillows.com/ (shameless plug) looks forward to the release.
