### ISSUE TITLE
Set 'blog parent page' for breadcrumbs

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/wpseo-woocommerce#17]
As explained by a customer:
"I would like to display blog posts as 'Home > Blog > Category'. But because the settings are set to display latest posts rather than static, the WP SEO plugin will only display 'Home > Category.'

To get around this, I am using your old wordpress breadcrumbs plugin as well, which allows to set a Blog Parent Page. But, this overrides custom breadcrumb set in the WP SEO plugin."

See https://secure.helpscout.net/conversation/16437704/8325/

**Comment by boblinthorst** [comment]
Closing, no longer relevant.
