### ISSUE TITLE
Console error when clicking WooCommerce in the Yoast SEO plugin menu.

### ISSUE THREAD

**Issue by martijnvaneeghem** [Yoast/wpseo-woocommerce#176]
RC5.8

When clicking the WooCommerce tab in the Yoast SEO plugin, there is a console error.

![woocommerce_seo_-_yoast_seo_ _bob_loblaw_s_law_blog_ _wordpress](https://user-images.githubusercontent.com/30408660/32660642-ede8900c-c623-11e7-8f0f-dd86e18d46bf.png)

![woocommerce_seo_-_yoast_seo_ _bob_loblaw_s_law_blog_ _wordpress](https://user-images.githubusercontent.com/30408660/32660580-c685572a-c623-11e7-945e-e0b20aa8cb04.png)

**Comment by Xyfi** [comment]
In `wpseo-woocommerce.php` on line 353 the `yst_plugin_tools` style is enqueued without a flat version postfix, causing this error. The style is enqueued anyway by `wordpress-seo` most likely.

**Comment by Xyfi** [comment]
Confirmed that this bug is present in version `5.7.1` in conjunction with Yoast SEO `5.7.1`.
