### ISSUE TITLE
Sale price not being displayed in Snippet Preview

### ISSUE THREAD

**Issue by jcomack** [Yoast/wpseo-woocommerce#187]
### What did you expect to happen?

When entering a sale price, with the start date being in the past and the end date being in the future, I'd like to see the sales price reflected in the Snippet Preview, especially if the sale price will be active for an extended period. However, I'm unsure if this is something we really want or not.

### What happened instead?

The regular price is displayed.

### How can we reproduce this behavior?

* Create a new product and ensure you have a price set
* Add `%%wc_price%%` to either the meta title or description in the Snippet Preview.
* Add a sale price with the start date in the past and the end date in the future.
* Notice that the price doesn't change.

### Technical info
* WordPress version: 4.9.1
* Yoast SEO version: 6.0

Related: https://github.com/Yoast/wpseo-woocommerce/pull/159

**Comment by jdevalk** [comment]
Don't think we should do this...
