### ISSUE TITLE
Declare required and supported WooCommerce version

### ISSUE THREAD

**Issue by amboutwe** [Yoast/wpseo-woocommerce#224]
WooCommerce informs users whether or not WooCommerce add-ons are compatible with the current version. They use two tags ([documented here](https://docs.woocommerce.com/document/create-a-plugin/#section-10)) which we do not include.

Example
```
* WC requires at least: 2.2
* WC tested up to: 3.3
```
![selection_372](https://user-images.githubusercontent.com/8060612/36325472-22b50174-1315-11e8-81ea-beb78a871683.png)

Related: https://github.com/Yoast/wpseo-local-woocommerce/issues/149

**Comment by amboutwe** [comment]
Please inform the customer of conversation # 309970 when this conversation has been closed.

**Comment by andizer** [comment]
A while ago I saw that yellow stuff underneath the WooCommerce thing in the plugins overview and I was curious how they achieved that. It's all custom code to get this done. 

I believe this is not a good first issue. Discussed the last part with @CarolineGeven and decided to remove that label.
