### ISSUE TITLE
og:brand not supported for og:type 'product'

### ISSUE THREAD

**Issue by monbauza** [Yoast/wpseo-woocommerce#225]
### What did you expect to happen?
OpenGraph markup generated by Yoast WooCommerce SEO to validate correctly in the Facebook Debug tool

### What happened instead?
The `og:brand` inserted by Yoast WooCommerce SEO doesn't seem to be supported for og:type 'product'. The Facebook debug tool return the following warning:

> The following properties are specified on the webpage but NOT supported for the specified 'og:type': og:brand

### How can we reproduce this behavior?
1. Go to "SEO > WooCommerce SEO"
2. Choose a WooCommerce product attribute in the Brand dropdown (see image one below)
3. Go to the edit screen of a WooCommerce product
4. Add a brand attribute to the product and save changes 
5. View the source code of the product and note the plugin has inserted the `og:brand` tag (see image two below)
6. Run the product page through [Facebook Debug tool](https://developers.facebook.com/tools/debug/) and notice a warning is shown

Image One

![image](https://user-images.githubusercontent.com/9658774/36776407-f6ab3a62-1c65-11e8-8816-3247b931d008.png)

Image Two

![image](https://user-images.githubusercontent.com/9658774/36776459-2829d2b0-1c66-11e8-9ab4-a1c04e00796d.png)

### Technical info
* WordPress version: 4.9.4
* Yoast SEO version: 6.3.1
* Yoast WooComerce SEO: 6.3

**Comment by gettek** [comment]
+1 on this!
Can we please have a rough date of when we may expect this fix?
