### ISSUE TITLE
Helpcenter is missing

### ISSUE THREAD

**Issue by PatrickYoast** [Yoast/wpseo-woocommerce#232]
### What did you expect to happen?
The help center to show up like it does in Yoast SEO

### What happened instead?
The help center is missing and a console error appeared
<img width="1498" alt="woocommerce_seo_-_yoast_seo_ _allplugins_test_ _wordpress" src="https://user-images.githubusercontent.com/14159618/37342665-89d365bc-26c5-11e8-9f06-752b3ac55192.png">

### How can we reproduce this behavior?

1. Install Yoast SEO Premium 7.1 RC2 and WooCommerce SEO 7.1 RC2.
2. Navigate to the WooCommerce SEO page.
3. See that help center is missing and find the error in the console (can take a couple of seconds to show up)

The same issue is there for:
News SEO: https://github.com/Yoast/wpseo-news/issues/382
Video SEO: https://github.com/Yoast/wpseo-video/issues/577

### Technical info
* WordPress version: 4.9.4
* Yoast SEO version: 7.1 RC 2

**Comment by moorscode** [comment]
Could not reproduce in latest version, at least the JavaScript error.
