### ISSUE TITLE
Meta description taken from the product description is truncated to 156 characters

### ISSUE THREAD

**Issue by rmarcano** [Yoast/wpseo-woocommerce#238]
### What did you expect to happen?
When there is no short product description or custom meta description on a product, the plugin will create a description from the regular product description, limited to 156 characters.

I expected this to be around 320 characters as per new Google meta description rules.

### What happened instead?
The meta description was limited to 156 characters

### How can we reproduce this behavior?
Create a new product with no custom meta description and no short description. The meta description should be created from the product description, truncated to 156 characters.

More info: https://github.com/Yoast/wpseo-woocommerce/blob/87ec65466a510e8158abbee4676f25e5da599da6/wpseo-woocommerce.php#L806

### Technical info
* WordPress version: 4.9.4
* Yoast SEO version: 7.1.1
* Yoast WooCommerce SEO version: 7.1

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 328739 when this conversation has been closed.

**Comment by moorscode** [comment]
This is no longer relevant, as Google has stopped testing with the larger description.

**Comment by Pcosta88** [comment]
Related: https://yoast.com/shorter-meta-descriptions/
