### ISSUE TITLE
Noindexed pages still visible in the sitemap

### ISSUE THREAD

**Issue by PatrickYoast** [Yoast/wpseo-woocommerce#239]
WooCommerce sets some pages (cart, my account) on `noindex, follow` (see `wc_page_noindex()` function), but those pages still appear in the Yoast SEO sitemap.

What we should do is when these pages are set to `noindex` we should remove them from the sitemap.

**Comment by omarreiss** [comment]
Good enhancement, without actual customers reporting this as an issue: wontfix
