### ISSUE TITLE
Console error Uncaught TypeError: Cannot read property 'ReplaceVar' of undefined error; on WooCommerce Product overview page

### ISSUE THREAD

**Issue by suascat** [Yoast/wpseo-woocommerce#242]
Following JavaScript errors are seen in the browser console while viewing products; 

WooCommerce > Products.

Uncaught TypeError: Cannot read property 'ReplaceVar' of undefined
    at yoastseo-woo-replacevars-590.min.js:1
    at Object.1 (yoastseo-woo-replacevars-590.min.js:1)
    at e (yoastseo-woo-replacevars-590.min.js:1)
    at a (yoastseo-woo-replacevars-590.min.js:1)
    at yoastseo-woo-replacevars-590.min.js:1

File path: wp-content/plugins/wpseo-woocommerce/js/yoastseo-woo-replacevars-590.min.js?ver=7.2

Screenshot:

![console](https://user-images.githubusercontent.com/9716719/38612472-83ad3c56-3da6-11e8-941b-f0722d756ee1.png)

### How can we reproduce this behavior?

1. Deactivate all other plugins except WooCommerce, Yoast SEO, WooCommerce SEO
2. Go to WooCommerce > Products (listing)
3. Inspect browser console

### Technical info
* WordPress version: 4.9.5
* Yoast SEO (free/premium) version: 7.2
* WooCommerce SEO: 7.2
* WooCommerce: 3.3.5

**Comment by priscillamc** [comment]
Please inform the customer of conversation # 381230 when this conversation has been closed.

**Comment by lp741** [comment]
follow still same problem

**Comment by moorscode** [comment]
I cannot reproduce this in Yoast SEO 9.0 / WooCommerce SEO 9.0.
