### ISSUE TITLE
No OG data for manufacturer

### ISSUE THREAD

**Issue by Michelle2403** [Yoast/wpseo-woocommerce#245]
![image](https://user-images.githubusercontent.com/22290584/39304859-709a3fc2-495b-11e8-8bd7-6de05fd1493b.png)

I'm not able to generate any OG data when it comes to 'manufacturer'. I have tried to set manufacturer based on 'product categories' and 'tags', but I don't see any OG data in the source code for manufacturer. 

It is not a regression. 

### Technical info
* WordPress version: 4.9.5
* Yoast SEO version: 7.4 rc2

**Comment by moorscode** [comment]
Closing this in favor of #128

**Comment by monbauza** [comment]
Is the OG tag for manufacturer expected to be outputted in any case? Even if the Manufacturer dropdown under SEO > WooCommerce is set to a product attribute, the OG tag for manufacturer is not generated (the itemprop tag is).

I try to find any documentation that specifies the manufacturer OG tag but didn't succeed.
