### ISSUE TITLE
Changelog doesn't show

### ISSUE THREAD

**Issue by benvaassen** [Yoast/wpseo-woocommerce#266]
When an update is available, you can click the "View version x.x details." link to see the changelog: 

![view](https://user-images.githubusercontent.com/11910661/43582407-a31c8740-965c-11e8-9cb5-f7a814d2f30f.png)

For WooCommerce SEO, the following changelog is shown: 

![changelog](https://user-images.githubusercontent.com/11910661/43582352-6e9ec406-965c-11e8-9211-3f3c4a177741.png)

@herregroen looked into this and the request doesn't go to MyYoast, but instead to WordPress.org. As far as he could see, this should be fixed in the plugin.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 424747 when this conversation has been closed.

**Comment by Pcosta88** [comment]
To view details of what changed in WooCommerce SEO see the changelog: https://yoast.com/wordpress/plugins/yoast-woocommerce-seo/change-log/

**Comment by jdevalk** [comment]
Fixed by 00a3e99667de6d11a0417e9a9812d2e5e27b4a6c
