### ISSUE TITLE
The Breadcrumbs Settings link in the WooCommerce SEO settings is broken

### ISSUE THREAD

**Issue by rmarcano** [Yoast/wpseo-woocommerce#267]
### What did you expect to happen?
When clicking on the link to the "Breadcrumbs Settings Page" in the WooCommerce SEO settings, I expected to be taken to the breadcrumbs settings page.

![woo-settings](https://user-images.githubusercontent.com/1044883/44127843-3d4e49ca-a00d-11e8-8fad-58949e6d4106.png)

### What happened instead?
I was taken to a page with the message "Sorry, you are not allowed to access this page."

![sorry](https://user-images.githubusercontent.com/1044883/44127740-cbb122a6-a00c-11e8-9b8f-ef9cc1a0a6f3.png)

### How can we reproduce this behavior?
Go to the WooCommerce SEO settings page and click on the "Breadcrumbs Settings page" link. See that the link does not work.

### Technical info
* WordPress version: 4.9.8
* Yoast SEO version: 8.0
* WooCommerce SEO version: 8.0

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 415581  when this conversation has been closed.

**Comment by rumejan** [comment]
Please inform the customer of conversation # 430098 when this conversation has been closed.
