### ISSUE TITLE
Add Open Graph type og:product output

### ISSUE THREAD

**Issue by IreneStr** [Yoast/wpseo-woocommerce#277]
Add the following open graph output to products:

```
<meta property="og:type" content="og:product" />
<meta property="product:price:amount" content="[amount]"/>
<meta property="product:price:currency" content="[currency]"/>
```

For docs, see https://developers.facebook.com/docs/payments/product/

**Comment by moorscode** [comment]
We already output:
```
<meta property="product:price:amount" content="[amount]"/>
<meta property="product:price:currency" content="[currency]"/>
```
And also:
`<meta property="og:type" content="product" />`

Facebook is a bit ambiguous what the value of `og:type` should be:

`og:type = product` vs `og:type = og:product`
https://developers.facebook.com/docs/reference/opengraph/object-type/product/
https://developers.facebook.com/docs/payments/product/

As it is mentioned 13 times on the `https://developers.facebook.com/docs/payments/product/` page, I think this is the one we should use..

/cc @jdevalk

**Comment by jdevalk** [comment]
agreed.
