### ISSUE TITLE
Removing product from API produces mySQL max_allowed_packet error due to Yoast notice

### ISSUE THREAD

**Issue by devonto** [Yoast/wpseo-woocommerce#279]
### What did you expect to happen?
Deleting products in bulk via the WooCommerce API should occur normally, without error

### What happened instead?
Products were deleted, but API response was erroneous and logs output as follows:

` mod_fcgid: stderr: WordPress database error Got a packet bigger than 'max_allowed_packet' bytes for query UPDATE `sco_usermeta` SET `meta_value` = 'a:1134:{i:0;a:2:{s:7:\\"message\\";s:569:\\"<h2>Make sure you don\\'t miss out on traffic!</h2><p>You just binned a Product. Search engines and other websites can still send traffic to your deleted post. You should create a redirect to ensure your visitors do not get a 404 error when they click on the no longer working URL. With Yoast SEO Premium, you can easily create such redirects.</p><p><a class=\\"button-primary\\" href=\\"https://yoa.st/1d0?php_version=7.1.21&platform=wordpress&platform_version=4.9.8&software=free&software_version=8.1&role=unknown&days_active=72\\" target=\\"_blank\\">Get Yoast SEO Premium</a></p>\\";s:7:\\"options\\";a:9:{s:4:\\"type\\";s:29:\\"notice-warning is-dismissible\\";s:2:\\"id\\";s:0:\\"\\";s:5:\\"nonce\\";N;s:8:\\"priority\\";d:0.5;s:9:\\"data_json\\";a:0:{}s:13:\\"dismissal_key\\";N;s:12:\\"capabilities\\";a:1:{i:0;s:20:\\"wpseo_manage_options\\";}s:16:\\"capability_check\\";s:3:\\"all\\";s:14:\\"yoast_branding\\";b:1;}}i:1;a:2:{s:7:\\"message\\";s:569:\\"<h2>Make sure you don\\'t miss out on traffic!</h2><p>You just binned a Product. Search engines and other websites can still send traffic to your deleted post. You should create a redirect to ensure your visitors do not get a 404 error when they click on the no longer working URL. With Yoast SEO Premium, you can easily create such redirects.</p><p><a class=\\"button-primary\\" href=\\"https://yoa.st/1d0?php_version=7.1.21&platform=wordpress&platform_version=4.9.8&software=free&software_version=8.1&role=unknown&days_active=72\\" target=\\"_blank\\">Get Yoast SEO Premium</a></p>\\";s:7:\\"options\\";a:9:{s:4:\\"type\\";s:29:\\"notice-warning is-dismissible\\";s:2:\\"id\\";s:0:\\"\\";s:5:\\"nonce\\";N;s:8:\\"priority\\";d:0.5;s:9:\\"data_json\\";a:0:{}s:13:\\"dismissal_key\\";N;s:12:\\"capabilities\\";a:1:{i:0;s:20:\\"wpseo_manage_options\\";}s:16:\\"capability_check\\";s:3:\\"all\\";s:14:\\"yoast_branding\\";b:1;}}i:2;a:2:{s:7:\\"message\\";s:569:\\"<h2>Make sure you don\\'t miss out on traffic!</h2><p>You just binned a Product. Search engines and other websites can still send traffic to your deleted post. You should create a redirect to ensure your visitors do not get a 404 error when they click on the no longer working URL. With Yoast SEO Premium, you can easily create such redirects.</p><p><a class=\\"button-primary\\" href=\\"https://yoa.st/1d0?php_version=7.1.21&platform=wordpress&platform_version=4.9.8&software=free&software_version=8.1&role=unknown&days_active=72\\" target=\\"_blank\\">Get Yoast SEO Premium</a></p>\\";s:7:\\"options\\";a:9:{s:4:\\"type\\";s:29:\\"notice-warning is-dismissible\\";s:2:\\"id\\";s:0:\\"\\";s:5:\\"nonce\\";N;s:8:\\"priority\\";d:0.5;s:9:\\"data_json\\";a:0:{}s:13:\\"dismissal_key\\";N;s:12:\\"capabilities\\";a:1:{i:0;s:20:\\"wpseo_manage_options\\";}s:16:\\"capability_check\\";s:3:\\"all\\";s:14:\\"yoast_branding\\";b:1;}}i:3;a:2:{s:7:\\"message\\";s:569:\\"<h2>Make sure you don\\'t miss out on traffic!</h2><p>You just binned a Product. Search engines and other websites can still send traffic to your deleted post. You should create a redirect to ensure your visitors do not get a 404 error when they click on the no longer working URL. With Yoast SEO Premium, you can easily create such redirects.</p><p><a class=\\"button-primary\\" href=\\"https://yoa.st/1d0?php_version=7.1.21&platform=wordpress&platform_version=4.9.8&software=free&software_version=8.1&role=unknown&days_active=72\\" target=\\"_blank\\">Get Yoast SEO Premium</a></p>\\";s:7:\\"options\\";a:9:{s:4:\\"type\\";s:29:\\"notice-warning is-dismissible\\";s:2:\\"id\\";s:0:\\"\\";s:5:\\"nonce\\";N;s:8:\\"priority\\";d:0.5;s:9:\\"data_json\\";a:0:{}s:13:\\"dismissal_key\\";N;s:12:\\"capabilities\\";a:1:{i:0;s:20:\\"wpseo_manage_options\\";}s:16:\\"capability_check\\";s:3:\\"all\\";s:14:\\"yoast_branding\\";b:1;}}i:4;a:2:{s:7:\\"message\\";s:569:\\"<h2>Make sure you don\\'t miss out on traffic!</h2><p>You just binned a Product. Search engines and other websites can still send traffic to your deleted post. You should create a redirect to ensure your visitors do not get a 404 error when they click on the no longer working URL. With Yoast SEO Premium, you can easily create such redirects.</p><p><a class=\\"button-primary\\" href=\\"https://yoa.st/1d0?php_version=7.1.21&platform=wordpress&platform_version=4.9.8&software=free&software_version=8.1&role=unknown&days_active=72\\" target=\\"_blank\\">Get Yoast SEO Premium</a></p>\\";s:7:\\"options\\";a:9:{s:4:\\"type\\";s:29:\\"notice-warning is-dismissible\\";s:2:\\"id\\";s:0:\\"\\";s:5:\\"nonce\\";N;s:8:\\"priority\\";d:0.5;s:9:\\"data_json\\";a:0:{}s:13:\\"dismissal_key\\";N;s:12:\\"capabilities\\";a:1:{i:0;s:20:\\"wpseo_manage_options\\";}s:16:\\"capability_check\\";s:3:\\"all\\";s:14:\\"yoast_branding\\";b:1;}}i:5;a:2:{s:7:\\"message\\";s:569:\\"<h2>Make sure you don\\'t miss out on traffic!</h2><p>You just binned a Product. Search engines and other websites can still send traffic to your deleted post. You should create a redirect to ensure your visitors do not get a 404 error when they click on the no longer working URL. With Yoast SEO Premium, you can easily create such redirects.</p><p><a class=\\"button-primary\\" href=\\"https://yoa.st/1d0?php_version=7.1.21&platform=wordpress&platform_version=4.9.8&software=free&software_version=8.1&role=unknown&days_active=72\\" target=\\"_blank\\">Get Yoast SEO Premium</a></p>\\";s:7:\\"options\\";a:9:{s:4:\\"type\\";s:29:\\"notice-warning is-dismissible\\";s:2:\\"id\\";s:0:\\"\\";s:5:\\"nonce\\";N;s:8:\\"priority\\";d:0.5;s:9:\\"data_json\\";a:0:{}s:13:\\"dismissal_key\\";N;s:12:\\"capabilities\\";a:1:{i:0;s:20:\\"wpseo_manage_options\\";}s:16:\\"capability_check\\";s:3:\\"all\\";s:14:\\"yoast_branding\\";b:1;}}i:6;a:2:{s:7:\\"message\\";s:569:\\"<h2>Make sure you don\\'t miss out on traffic!</h2><p>You just binned a Product. Search engines and other websites can still send traffic to your deleted post. You should create a redirect to ensure your visitors do not get a 404 error when they click on the no longer working URL. With Yoast SEO Premium, you can easily create such redirects.</p><p><a class=\\"button-primary\\" href=\\"https://yoa.st/1d0?php_version=7.1.21&platform=wordpress&platform_version=4.9.8&software=free&software_version=8.1&role=unknown&days_active=72\\" target=\\"_blank\\">Get Yoast SEO Premium</a></p>\\";s:7:\\"options\\";a:9:{s:4:\\"type\\";s:29:\\"notice-warning is-dismissible\\";s:2:\\"id\\";s:0:\\"\\";s:5:\\"nonce\\";N;s:8:\\"priority\\";d:0.5;s:9:\\"data_json\\";a:0:{}s:13:\\"dismissal_key\\";N;s:12:\\"capabilities\\";a:1:{i:0;s:20:\\"wpseo_manage_options\\";}s:16:\\"capability_check\\";s:3:\\"all\\";s:14:\\"yoast_branding\\";b:1;}}i:7;a:2:{s:7:\\"message\\";s:569:\\"<h2>Make sure y...`

### How can we reproduce this behavior?
Use API to delete products in bulk

Can you provide a link to a page which shows this issue?
N/A

### Technical info
* WordPress version: 4.9.8
* WooCommerce version: 3.4.5
* Yoast SEO version: 8.2
* Yoast SEO WooCommerce version: 8.2

**Comment by CarolineGeven** [comment]
Thanks for reporting this issue. We've been able to reproduce the issue and have therefore labeled the issue as a bug.

Unfortunately we're not able to fix this at short notice. Currently we're focusing on issues that affect many users. We've concluded that this issue is not experienced by many users, therefore we are not able to fix this short-term. However, if more users are affected by this bug, we'll of course revisit this issue.

**Comment by CarolineGeven** [comment]
A work around: before you do the bulk delete, you can unhook the following action: 
https://github.com/Yoast/wordpress-seo/blob/b26284bbe7ee726d3fa2330928c99ad019f9fef9/admin/watchers/class-slug-change-watcher.php#L30

**Comment by devonto** [comment]
Unfortunately, since this is done via the standard WooCommerce API, it's not possible to unhook on request.

For now, I will unhook it globally.

**Comment by Djennez** [comment]
From a few tests I don't seem to be able to reproduce this behavior anymore on the 11.7 versions of our plugins. I will close this for now but please reopen / comment if this behavior is still present.

**Comment by ifnull** [comment]
```WordPress database error Got a packet bigger than 'max_allowed_packet' bytes for query UPDATE `wp_usermeta` SET `meta_value` = 'a:375:{i:0;a:2:{s:7:\"message\";s:719:\"<h2>Make sure you don\'t miss out on traffic!</h2><p>You just deleted a Product. Search engines and other websites can still send traffic to your deleted post. You should create a redirect to ensure your visitors do not get a 404 error when they click on the no longer working URL. With Yoast SEO Premium, you can easily create such redirects.</p><p><a class=\"yoast-button-upsell\" href=\"https://yoa.st/1d0?php_version=7.4&platform=wordpress&platform_version=5.8.1&software=free&software_version=17.2&days_active=91-180&user_language=en_US\" target=\"_blank\">Get Yoast SEO Premium<span class=\"screen-reader-text\">(Opens in a new browser tab)[...]```
