### ISSUE TITLE
[Feature Request or Issue] Count the short product description in WooCommerce as part of the SEO and Readability Scores

### ISSUE THREAD

**Issue by CarolineGeven** [Yoast/wpseo-woocommerce#280]
Copied from https://github.com/Yoast/wordpress-seo/issues/5474

Yoast SEO analyzes the the short description for being too long or too short. It does not analyze anything else. We should add the ability for the plugin to scan for text length, keywords, etc. 

**Default Setting: Long and Short Descriptions Blank** 

![3](https://cloud.githubusercontent.com/assets/8238074/18181603/f0647a2e-7059-11e6-9d75-f2975a8e4885.jpg)

**Short Description Only: SEO Score**

![text length](https://cloud.githubusercontent.com/assets/8238074/18181630/0efbc64a-705a-11e6-945d-3396ea3b9ab8.jpg)

**Short Description Only: Yoast adds the short description to the snippet preview as a meta description. Then throws out a red dot.**

![1](https://cloud.githubusercontent.com/assets/8238074/18181783/ea711d1a-705a-11e6-8646-2ff69ffdb41d.jpg)

**Short Description Only: Readability Score** Readability shows the same result if short description left blank

![screen shot 2016-09-01 at 3 38 26 pm](https://cloud.githubusercontent.com/assets/8238074/18181648/27a194fe-705a-11e6-8927-36f04e72b64f.png)

Images, Keywords and alt-tags are also not recognized in the short description

![screen shot 2016-09-01 at 3 46 58 pm](https://cloud.githubusercontent.com/assets/8238074/18181869/668720fc-705b-11e6-87f2-e07a3a70d0c3.png)

**Comment by CarolineGeven** [comment]
Please inform the customer of conversation # 145066 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 147171 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 150038 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 154594 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 160063 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 160722 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 162500 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 161289 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 172513 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 175325 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 181146 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 183184 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 185859 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 193259 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 191158 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 194392 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 201018 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 208322 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 213144 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 214288 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 217783 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 226700 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 408762 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 433093 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 435121 when this conversation has been closed.

**Comment by mayada-ibrahim** [comment]
Please inform the customer of conversation # 435736 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 437242 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 441338 when this conversation has been closed.

**Comment by moorscode** [comment]
When using the `%%excerpt%%` replacement variable, the short description will be used as the OG description. This description has additional checks that are not specifically applied to the short product description.

We do supply an option about the length of the short description, also stating when it is too long.

_The mention that the short description would not be used as "description" can be resolved with the `Excerpt` replacement variable._

Using this method the short product description can be set with more certainty on keyword distribution and length.

You can set this in the Social Appearance settings of a product description to be the default.

We cannot know how this field is used on the theme.
It is meant to be an additional short(er) description of what the product description (main content field) is about. The real content should be in there. The default WooCommerce themes (WooCommerce without specific theme, Storefront, WooTheme) work this way.
