### ISSUE TITLE
Social preview does not load when visual editor is disabled

### ISSUE THREAD

**Issue by amboutwe** [Yoast/wpseo-woocommerce#282]
### What did you expect to happen?
Social preview to show

### What happened instead?
No social preview. Error `ReferenceError: tinyMCE is not defined`
![selection_210](https://user-images.githubusercontent.com/8060612/46303963-944bc900-c56a-11e8-9a21-3ad9d94a882d.png)

### How can we reproduce this behavior?

1. Install and activate WooCommerce and Yoast SEO Premium
2. Go to Users > Your Profile
3. Chec Disable the visual editor when writing
4. Go to Admin > Products > Add New
5. In Yoast metabox, switch to the social tab. Preview works.
6. Install and activate Yoast SEO: WooCommerce.
7. Go to Admin > Products > Add New
8. In Yoast metabox, switch to the social tab. No preview. Error

Can you provide a link to a page which shows this issue?
n/a

### Technical info
* WordPress version: 4.9.8
* Yoast SEO version: 8.3 (premium required)
* Yoast SEO WooCommerce version: 8.3
* WooCommerce version: 3.4.5

Regression: Worked with 8.0 Prem/Woo. Stopped in 8.1

**Comment by amboutwe** [comment]
Please inform the customer of conversation # 428773 when this conversation has been closed.

**Comment by moorscode** [comment]
Cannot reproduce in 9.0
