### ISSUE TITLE
[Feature Request] Output the "Brand" and "Manufacturer" properties in the JSON-LD Product schema

### ISSUE THREAD

**Issue by rmarcano** [Yoast/wpseo-woocommerce#284]
The WooCommerce SEO plugin has a feature that lets users specify a Brand and Manufacturer for Products. However, this information is not output in the JSON-LD product schema. 

It would be useful to output this information as JSON-LD, since [Google supports the "brand" property](https://developers.google.com/search/docs/data-types/product) for the Rich Results for Products.

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 432970 when this conversation has been closed.

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 435239 when this conversation has been closed.

**Comment by monbauza** [comment]
Currently, the brand and manufacturer properties are outputted using microdata, however, these don't seem to be detected in the Google Structured Data Testing tool.

Plugins versions: Yoast SEO v9.7, WooCommerce SEO v9.7 and WooCommerce v3.5.5

![image](https://user-images.githubusercontent.com/9658774/53624979-2df2d180-3c02-11e9-9d74-58a11ac16842.png)

**Comment by monbauza** [comment]
Please inform the customer of conversation # 479335 when this conversation has been closed.

**Comment by michaelbriantina** [comment]
Please inform the customer of conversation # 479732 when this conversation has been closed.

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 483399 when this conversation has been closed.

**Comment by rmarcano** [comment]
It seems that Google is not recognizing the "Brand" schema because the Microdata the WooCommerce plugin is outputting is not correctly formatted. 

According to the [Google documentation](https://developers.google.com/search/docs/data-types/product), the microdata should have the following format (notice that the "name" apparently needs to be nested inside the "brand" itemprop.):
```
  <div itemprop="brand" itemtype="http://schema.org/Thing" itemscope>
      <meta itemprop="name" content="ACME" />
  </div>
```
The microdata the plugin outputs has the following format:
`<p itemprop="brand">ACME</p>`
 
In this case, the "name" is not nested inside the "brand".

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 483904 when this conversation has been closed.

**Comment by michaelbriantina** [comment]
Please inform the customer of conversation # 483845 when this conversation has been closed.

**Comment by priscillamc** [comment]
Please inform the customer of conversation # 484632  when this conversation has been closed.

**Comment by michaelbriantina** [comment]
Please inform the customer of conversation # 485695 when this conversation has been closed.

**Comment by Nick776** [comment]
follow

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 487179 when this conversation has been closed.

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 556105 when this conversation has been closed.

**Comment by jdevalk** [comment]
This was fixed quite a while ago when we introduced the new schema.
