### ISSUE TITLE
Helpscout gets timed out in Safari, IE11, Edge

### ISSUE THREAD

**Issue by dariaknl** [Yoast/wpseo-woocommerce#292]
### How can we reproduce this behavior?
1. Install and activate wpseo-woocommerce-9.0
2. Go to SEO -> WooCommerce SEO.
3. Open console and check error (screenshot from Edge browser):
![image 29](https://user-images.githubusercontent.com/19681708/47856966-c4e08600-dde8-11e8-8df7-7083cc1687e4.png)

4. It results in the error in helpscout when you enter search request:
<img width="477" alt="screen shot 2018-11-01 at 15 14 40" src="https://user-images.githubusercontent.com/19681708/47857041-f1949d80-dde8-11e8-9e94-ca511ec52204.png">

Reproduced in Safari, IE11, Edge.

### Technical info
* WordPress version: 4.9.8
* Yoast SEO version: 9.1. RC3

**Comment by moorscode** [comment]
This *should* work as the mentioned URL provides the following headers:
```
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
Access-Control-Allow-Methods: GET, POST, PUT, DELETE
Access-Control-Allow-Origin: *
```

This is not an issue that is affecting any customers.

**Comment by moorscode** [comment]
The `localhost` part is the thing that triggered me. If this is reproduced on a domain (test domain or real domain), we should re-open and look into it.
