### ISSUE TITLE
Helpscout overlaps with WP version

### ISSUE THREAD

**Issue by dariaknl** [Yoast/wpseo-woocommerce#293]
### How can we reproduce this behavior?
1. Go to SEO -> WooCommerce SEO.
2. Check helpscout in Edge and IE11:

Edge
![image 30](https://user-images.githubusercontent.com/19681708/47857710-a7142080-ddea-11e8-8d2c-f6dd1acb5017.png)

IE11
![image 31](https://user-images.githubusercontent.com/19681708/47857718-ab403e00-ddea-11e8-9c39-bcae3ca34c11.png)

Question mark overlaps with WP version.

### Technical info
* WordPress version: 4.9.8
* WooCommerce SEO: 9.0

**Comment by atimmer** [comment]
We're intending to remove the question mark: https://github.com/Yoast/wpseo-woocommerce/issues/233. So let's not spend time fixing this.
