### ISSUE TITLE
Cannot edit woocommerce product data

### ISSUE THREAD

**Issue by artalacarte** [Yoast/wpseo-woocommerce#301]
![product-data](https://user-images.githubusercontent.com/45153633/48679439-267d5000-eb5e-11e8-9350-4deab3d0b5e3.JPG)
### How can we reproduce this behavior?

Can you provide a link to a page which shows this issue? All product pages

### Technical info
* WordPress version: 4.9.8
* Yoast SEO version:9.1

**Comment by Djennez** [comment]
We use GitHub exclusively for well-documented bug reports or feature requests. This is not a support forum.

If you feel like your bug or enhancement is a valid one and should be reviewed by us, then please use the provided templates, read our [contribution guidelines](https://github.com/Yoast/wordpress-seo/blob/trunk/.github/CONTRIBUTING.md) and submit a new issue.

Thank you for your understanding.
