### ISSUE TITLE
[Enhancement] When WooCommerce SEO is installed remove ads for it

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-woocommerce#302]
**When WooCommerce SEO is installed, ads for it still appear.** 
****
**Yoast SEO Free and WooCommerce SEO installed**

<img width="1179" alt="screen shot 2018-11-19 at 9 48 59 am" src="https://user-images.githubusercontent.com/8238074/48714279-5a995500-ebe0-11e8-8133-e57a158e356b.png">

**Ads for WooCommerce SEO appear**

<img width="1267" alt="screen_shot_2018-11-19_at_9_48_48_am" src="https://user-images.githubusercontent.com/8238074/48714302-70a71580-ebe0-11e8-9d59-4f767e2acacc.png">

Happens with newest versions

### Technical info
* WordPress version: 4.9.8
* Yoast SEO version: 9.1
* WooCommerce SEO: 9.1

**Comment by jdevalk** [comment]
Honestly not really interested in fixing this.
