### ISSUE TITLE
Console errors in Products

### ISSUE THREAD

**Issue by dariaknl** [Yoast/wpseo-woocommerce#303]
### How can we reproduce this behavior?
1. Go to create new product in Woocommerce.
2. Click Add new.
3. In Edit window switch between Text and Visual editors.
<img width="608" alt="screenshot 2018-11-21 at 11 56 04" src="https://user-images.githubusercontent.com/19681708/48837001-7f2e3200-ed84-11e8-906b-23c01c33dea3.png">
4. Check console:
<img width="775" alt="screenshot 2018-11-21 at 11 56 58" src="https://user-images.githubusercontent.com/19681708/48837030-90773e80-ed84-11e8-984e-90e2f8e1769e.png">

### Technical info
* WordPress version: 4.9.8
* Yoast SEO version: 9.3-beta1

**Comment by IreneStr** [comment]
Probably related to the fix in #297

**Comment by hansjovis** [comment]
> Probably related to the fix in #297

Most probably. I am going to look into it!
