### ISSUE TITLE
Syntax error in IE11

### ISSUE THREAD

**Issue by dariaknl** [Yoast/wpseo-woocommerce#305]
### How can we reproduce this behavior?

1. Activate WooCommerce 3.5.2.
2. Activate Yoast SEO 9.3 beta2
3. Activate Yoast WooCommerce SEO  9.3 beta2.
4. Go to products overview page in IE11.
5. Check console:

![image 51](https://user-images.githubusercontent.com/19681708/49376470-a501f200-f707-11e8-8b1b-ccddcfba3461.png)

**Comment by andizer** [comment]
We don't support IE11 anymore :)
