### ISSUE TITLE
Help Scout does not work in IE11

### ISSUE THREAD

**Issue by dariaknl** [Yoast/wpseo-woocommerce#307]
### How can we reproduce this behavior?
1. Activate wpseo-woocommerce plugin.
2. In IE11 go to SEO - WooCommerce SEO.
3. Scroll to down to Help and check console:
![image 53](https://user-images.githubusercontent.com/19681708/50004897-da7cca00-ffa8-11e8-82b6-6517c05e49d7.png)

The issue occurs for all our addons in IE11.

**Comment by andizer** [comment]
We stopped supporting IE11
