### ISSUE TITLE
[Feature Request] Provide integration with Easy Digital Downloads EDD

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-woocommerce#310]
With the WooCommerce SEO users must have use it with WooCommerce.  

Easy Digital Downloads is another eCommerce plugin. 

We should provide integration of the WooCommerce SEO plugin with Easy Digital Downloads EDD

This will help improve UX and technical SEO for EDD's downloads.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 455697 when this conversation has been closed.

**Comment by tacoverdo** [comment]
No.
