### ISSUE TITLE
[Feature request] Add Products SEO Overview in the WordPress Dashboard

### ISSUE THREAD

**Issue by mariusghitulescu** [Yoast/wpseo-woocommerce#312]
For websites with products only (without posts), the Yoast SEO Posts Overview in the dashboard serves no purpose. We might add a similar widget for Products, so webmasters could easily get an idea of how well the product pages are optimized.

It could be a new widget, similar to the Posts Overview. We might also extend the current widget to include Products Overview too.

![2019-01-08 15_03_02](https://user-images.githubusercontent.com/4171016/50832797-f3825c00-1357-11e9-8250-da264cc95753.png)

**Comment by Pcosta88** [comment]
related https://github.com/Yoast/wordpress-seo/issues/8851

**Comment by Pcosta88** [comment]
https://github.com/Yoast/design/issues/312
