### ISSUE TITLE
[Feature Request] Add support for product:condition and product:retailer_item_id 

### ISSUE THREAD

**Issue by monbauza** [Yoast/wpseo-woocommerce#313]
Facebook requires a list of Open Graph tags for catalogs https://www.facebook.com/business/help/1175004275966513?helpref=faq_content Most of the tags are already outputted by the Yoast SEO and WooCommerce SEO plugins, however, there are two tags that are missing: `product:condition` and `product:retailer_item_id`

It'd be nice if we could add support for them as it would prevent customers already running Yoast SEO and WooCommerce SEO from using a 3rd party plugin to generate only those two tags.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 509896 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 520945 when this conversation has been closed.

**Comment by amboutwe** [comment]
Please inform the customer of conversation # 535386 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 551249 when this conversation has been closed.

**Comment by mayada-ibrahim** [comment]
Please inform the customer of conversation # 566899 when this conversation has been closed.

**Comment by friendorfoley** [comment]
I'm new to GitHub but I am also having the issue that Yoast WooCommerce is not pulling through the `product:retailer_item_id `. This is preventing me from creating shoppable instagram products as I cannot pull the catalogue through to Facebook from WordPress, are there any indications as to when this will be implemented?

**Comment by jdevalk** [comment]
I've implemented `product:retailer_item_id` in #457 and `product:condition` in #461
