### ISSUE TITLE
Cannot remove breadcrumbs due to override from plugin

### ISSUE THREAD

**Issue by uprise10** [Yoast/wpseo-woocommerce#317]
### What did you expect to happen?
When using the correct remove_action calls, the breadcrumbs should not be shown in the frontend, since we already output the breadcrumbs on a different place.

### What happened instead?
Breadcrumb still appear on the original spot, due to the `woocommerce_before_main_content` action.

### How can we reproduce this behavior?
 - Add custom breadcrumbs with the `yoast_breadcrumb()` function on every wanted place in the frontend.
 - Try to remove the default WooCommerce breadcrumbs by using this piece of code:

```
add_action( 'init', function () {
    remove_action( 'woocommerce_before_main_content', 'woocommerce_breadcrumb', 20 );
    remove_action( 'woocommerce_before_main_content', [ 'Yoast_WooCommerce_SEO', 'show_yoast_breadcrumbs' ], 20 );
} );
```

### Technical info
* WordPress version: 5.0.3
* Yoast SEO version: 9.5

Maybe related? #298 or #150

**Comment by jdevalk** [comment]
@uprise10 could you test if this still doesn't work? Would be happy to fix it :)

**Comment by jdevalk** [comment]
Awesome, closing.
