### ISSUE TITLE
[Enhancement] Provide a specific Readability Analysis for Product Pages

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-woocommerce#320]
The plugin outputs two SEO/Readability checks. It will output a singular check for length in the short product description area. Specifically, it looks at word count and considers 0 as having no words, 1-19 as short, 20-49 as good, and 50+ as long. 

If you added a product gallery the plugin will check it for alt-attributes.

However, if research is done on product pages we may discover more specific kinds of readability things to look for. 

We could then provide a specific Readability Analysis for Product Pages to enhance the WooCommerce SEO plugin's abilities.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 475091 when this conversation has been closed.

**Comment by moorscode** [comment]
If there are no specific needs or requests in an issue I'm going to have to close it.

This thing you describe is something that is determining what needs our attention in the broad sense of the company and should not have to be in issue format.

In short: missing something specific.
