### ISSUE TITLE
Prepare for PHP 5.2-5.5 drop

### ISSUE THREAD

**Issue by IreneStr** [Yoast/wpseo-woocommerce#330]
Mimic [the changes that were done on wordpress-seo](https://github.com/Yoast/wordpress-seo/pull/12129). 

This includes at least:
- [ ] Change `dist` from `trusty` to `xenial`. But explicitly use 'trusty' in the 5.6 test.
- [ ] Add mysql as service, because it is not included by default in xenial.
- [ ] Remove multisite from the 7.3 build that doesn't run the coverage.
- [ ] Remove PHP 5.3 build
- [ ] Remove PHP 7.0 build
- [ ] Use `WP_VERSION=latest` instead of `WP_VERSION=4.9`/`WP_VERSION=5.0`
- [ ] Set the wordpress clone depth to 1 instead of 50 to speed up the build 
     - (see https://github.com/Yoast/wordpress-seo/pull/12129/files#diff-354f30a63fb0907d4ad57269548329e3L154)
- [ ] Create 2 allowed failures instead of 1: one with `php: nightly` and `env: WP_VERSION=latest`, and one with `php: 7.3` and `env: WP_VERSION=master`. That way, we can distinguish between failures caused by the php build, and failures caused by the WP build. 
     - (See https://github.com/Yoast/wordpress-seo/pull/12129/files#diff-354f30a63fb0907d4ad57269548329e3R100)
- [ ] Make the use of phpunit more explicit: use `if [[ "$PHPUNIT" == "1" ]]; then` instead of `if [[ "$COVERAGE" != "1" ]]; then`. 
     - See https://github.com/Yoast/wordpress-seo/pull/12129/files#diff-354f30a63fb0907d4ad57269548329e3L233. 
     - [ ] Set 'PHPUNIT=1' to all builds that currently don't have 'COVERAGE=1'

Blocked by #319

**Comment by andizer** [comment]
Fixed in #433
