### ISSUE TITLE
Make PHPUnit work for new VVV installations

### ISSUE THREAD

**Issue by IreneStr** [Yoast/wpseo-woocommerce#332]
Running PHPUnit with a new VVV installation leads to a lot of errors. The command exits with exitcode 255. This might have to do with the configutation in the bootstrap file, [like in wordpress-seo](https://github.com/Yoast/wordpress-seo/pull/12327).

**Comment by johannadevos** [comment]
Both @jdevalk and myself couldn't replicate this issue in the `one.wordpress.test` installation. PHPUnit works without problems. Therefore, I'm closing this issue.
