### ISSUE TITLE
Only provide Product Attributes as an option for Manufacturer

### ISSUE THREAD

**Issue by moorscode** [Yoast/wpseo-woocommerce#333]
We currently provide a list of sources for the Manufacturer, most of them don't make much sense.

Actions:
- Only provide a list of Product Attributes to chose from in the Manufacturer dropdown
- Provide copy to instruct the user how to add new options to the list (to be determined)
  - Do we want to provide a one-button option to create a "Manufacturer" attribute on the Product Attributes?

Needs decision:
- How do we want to handle upgrades in a website where one of the options is selected which is no longer available?
  - Present the option anyway, and remove it once it has been changed to something else
  - Show a notification about the option not being the optimal one and suggest to change it

Technical specifications for: https://github.com/Yoast/wpseo-woocommerce/issues/128

**Comment by moorscode** [comment]
@thijsdevalk for your input on the user-flow.

**Comment by jdevalk** [comment]
Fixed this in #455.
