### ISSUE TITLE
[Feature Request] Add support for SKU in the Product structured data

### ISSUE THREAD

**Issue by rmarcano** [Yoast/wpseo-woocommerce#335]
Google supports SKU as a property for the [Product structured data type](https://developers.google.com/search/docs/data-types/product). 

It would be useful to add support for this in the WooCommerce SEO plugin.

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 484005 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 507386 when this conversation has been closed.

**Comment by Pcosta88** [comment]
I think we can close this. We output SKU w/ 11.2.1 of Yoast and  11.2 of WooCommerce.

1. Add SKU on  WooCommerce

<img width="827" alt="Screen Shot 2019-05-22 at 2 53 30 PM" src="https://user-images.githubusercontent.com/8238074/58200702-60f8ae80-7ca1-11e9-9f74-9400a387fbed.png">


2. See it shown

<img width="1355" alt="Screen Shot 2019-05-22 at 2 52 34 PM" src="https://user-images.githubusercontent.com/8238074/58200712-648c3580-7ca1-11e9-9eb3-e1e73ba7c48d.png">

**NOTE**
I have seen where Google Structured Data outputs a warning for SKU. I am not sure if certain products or other metadata also requires a SKU  OR IF Google tosses out a warning  on all products if it lacks SKU

**Comment by edwintoo** [comment]
In addition, please consider support for GTIN (which encompasses UPC/EAN/ISBN etc): https://schema.org/gtin

**Comment by truchosky** [comment]
> In addition, please consider support for GTIN (which encompasses UPC/EAN/ISBN etc): https://schema.org/gtin

+1 to this, add support for gtin, mpn or isbn

**Comment by Djennez** [comment]
So SKU exists and is part of WC (based on this thread). Closing this.

Support request for isbn, etc. is here: https://github.com/Yoast/wpseo-woocommerce/issues/358
