### ISSUE TITLE
Schema output improvements

### ISSUE THREAD

**Issue by jdevalk** [Yoast/wpseo-woocommerce#337]
### What do we need to change?
As https://github.com/Yoast/wordpress-seo/pull/12456 is merged, we should make some changes to the schema we output for Woo. 

#### Add Woo Product blob to our graph
With [this change](https://github.com/woocommerce/woocommerce/pull/22554) in Woo, we have proper `@id`'s for the Woo Product blob. This means we can quite easily add the Woo product blob to our Graph.

Should be about as simple as this:
```
"mainEntity" : { "@id" : "https://www.example.com/example-page/#product" }
```

#### Change the page `@type` on selected pages
We can change / add to the page `@type` on some pages.

- [x] Add Woo Product blob to our graph and make it the main entity.
- [x] Add `CheckoutPage` to page type array on checkout.
- [x] Add `ItemPage` to page type on product pages.

**Comment by jono-alderson** [comment]
I think the Woo parameters (including the ID) are still escaped (i.e., `\/value\/` rather than `/value/`); might need to experiment to make sure that things work as expected.
