### ISSUE TITLE
Fatal error: Call to undefined method WPSEO_Utils::schema_output()

### ISSUE THREAD

**Issue by dariaknl** [Yoast/wpseo-woocommerce#343]
### How can we reproduce this behavior?
1. Install and activate Yoast SEO 11.0 RC2.
2. Install and activate Woocommerce 11.0 RC2.
3. Browse to 404 page, Fatal is thrown:

<img width="1555" alt="Screenshot 2019-04-10 at 13 28 27" src="https://user-images.githubusercontent.com/19681708/55875130-89ff2d00-5b94-11e9-8881-a52f35e13f2e.png">

**Comment by jdevalk** [comment]
I think this is fixed when you use Yoast SEO RC3.

**Comment by dariaknl** [comment]
Re-tested with RC3, issue is gone.

**Comment by Tofandel** [comment]
This is back on the latest version
