### ISSUE TITLE
Schema product attribute duplication

### ISSUE THREAD

**Issue by jono-alderson** [Yoast/wpseo-woocommerce#345]
We output `price` and `priceCurrency` properties on `offer`, but _also_ output those in the `priceSpecification` property of the offer. At least, that's the case in our [example graphs](https://developer.yoast.com/schema-documentation/specification/#examplegraphs). 

That makes it faffy to support multi-currency/multi-price/varying-availability products.

Can we ascertain whether this is a real bug in the plugin, and if so, resolve?

**Comment by jono-alderson** [comment]
We should update our example graph code on https://developer.yoast.com/schema-documentation/specification/#examplegraphs when resolved.

**Comment by jono-alderson** [comment]
Update: This looks like native Woo output. Do we need to disable, and to build / fall back onto our own solution?

**Comment by jdevalk** [comment]
Can just filter Woo's output.

**Comment by jono-alderson** [comment]
Super. Suggested (example) markup for the `offers` node is:

```
"offers": [{
    "@type": "Offer",
    "priceValidUntil": "2020-12-31",
    "priceCurrency": ["USD","GBP"],
    "priceSpecification": [{
        "@type": "PriceSpecification",
        "price": "20.00",
        "priceCurrency": "USD",
        "valueAddedTaxIncluded": "false"
    }, {
        "@type": "PriceSpecification",
        "price": "999.99",
        "priceCurrency": "GBP",
        "valueAddedTaxIncluded": "false"
    }],
    "availability": "https://schema.org/InStock",
    "url": "https://example.com/product/vneck-tee/",
    "seller": {
        "@id": "https://example.com/#organization"
    }
}]
```
