### ISSUE TITLE
[Feature Request] Provide ability to extend OpenGraph Product tags to non-Product pages like Bookings or other Custom Post Types

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-woocommerce#346]
WooCommerce SEO outputs some specific opengraph OG tags on product pages. 

We should provide ability to extend OpenGraph Product tags to non-Product pages like Bookings or other Custom Post Types. A filter might be the best option. 

This would help improve the technical SEO of the page.

**Comment by jdevalk** [comment]
I don't see the use case for this? I'd like more explicit examples of what you're trying to reach and who is requesting this.

**Comment by Pcosta88** [comment]
Use Cases

Travel Agency who has travel packages set-up on a CPT. They could use the OG product brand to better market themselves in Facebook. Same with Pinterest. 

Product Landing Pages. So rather instead of creating a product page out of WooCommerce (as you do not want the checkout features) you create one say using the Portfolio CPT. This could be done for niche and custom services which do not lend themselves easily to a standard eCommerce solution. 
Thinking like artists or photographers.

**Comment by vladoa** [comment]
This is a very good use case @Pcosta88 !
@jdevalk you guys provided many filters here https://gist.github.com/amboutwe/811e92b11e5277977047d44ea81ee9d4 , including yoast_change_opengraph_type.

I am not sure if this filter actually covers what was initially suggested in this issue, but if not, it would be nice to add it.
