### ISSUE TITLE
Add template variable for product 'long' description

### ISSUE THREAD

**Issue by monbauza** [Yoast/wpseo-woocommerce#347]
## Is your feature request related to a problem? Please describe.
There may be cases where users would like the plugin to generate an automatic meta description based on the main (long) description they've entered for their WooCommerce product. 

The `%%excerpt%%` variable does the job IF the product short description hasn't been entered. However, if the product short description is provided, the`%%excerpt%%` variable currently outputs the short description instead of the main (long) one.

![image](https://user-images.githubusercontent.com/9658774/56199056-6d537100-603c-11e9-9b65-bd47e988fca9.png)

## Describe the solution you'd like
It'd be helpful to have a specific template variable to output the product main (long) description.

As the WooCommerce SEO add-on provides the `%%wc_shortdesc%%` variable, we could:
- Make the `%%excerpt%%` variable always output the product main (long) description
- Add a new variable to the WooCommerce SEO add-on, , i.e. `%%wc_longdesc%%`

Either of the above proposals would allow users to choose the description (short or long) they'd like to output

**Comment by tacoverdo** [comment]
Transferred issue from wordpress-seo repo to this repo.

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 515892  when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation #  537954 when this conversation has been closed.

**Comment by jdevalk** [comment]
Honestly I don't see the use case here. If you need this, than it means you _do_ have a short description, but you don't want to use it for the meta description? That doesn't make sense in any way and sounds like people are abusing the short description field. Closing.
