### ISSUE TITLE
[Feature Request] Add WooCommerce Template Variables like wc_sku into slug or permalink

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-woocommerce#352]
WooCommerce has template variables here https://kb.yoast.com/kb/yoast-wordpress-seo-titles-metas-template-variables/.

But adding them into the slug or going to SEO-Permalinks-Product-Custom fields fails to make the sku show. 

We should provide the ability to add template variables from WooCommerce into the product permalinks or slugs.

This can help with technical and content SEO

**Comment by Pcosta88** [comment]
related https://github.com/Yoast/wordpress-seo/issues/10567

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 496352 when this conversation has been closed.

**Comment by jdevalk** [comment]
Yeah you can't and will never be able to use them in slugs, due to a lot of constraints. Sorry.
