### ISSUE TITLE
[Feature Request] Output the aggregateRating schema

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/wpseo-woocommerce#357]
Output the aggregateRating schema: https://schema.org/AggregateRating

This can help with the Technical SEO of the plugin.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 498306 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 498739 when this conversation has been closed.

**Comment by suascat** [comment]
Please inform the customer of conversation # 502643 when this conversation has been closed.

**Comment by jono-alderson** [comment]
We already do this :)

**Comment by Pcosta88** [comment]
@jono-alderson I am confused. I am not seeing it listed in the schema for WooCommerce SEO or Yoast SEO https://developer.yoast.com/schema-documentation/

**Comment by Pcosta88** [comment]
**UPDATED**

**1. WooCommerce when it is the only plugin active outputs an AggregateRating**

_WooCommerce Active_
<img width="802" alt="Screen Shot 2019-05-09 at 9 39 51 AM" src="https://user-images.githubusercontent.com/8238074/57458002-9aabcd00-723e-11e9-99fe-51eb3549b3ef.png">

_See aggregateRating_

<img width="1477" alt="Screen Shot 2019-05-09 at 9 39 37 AM" src="https://user-images.githubusercontent.com/8238074/57458021-a1d2db00-723e-11e9-9983-90980bb2a31c.png">


**2. When you have Yoast SEO active the json+ld schema block still does not change**

**3. Activate WooCommerce SEO and it appears we take over that WooCommerce schema block**

_Yoast and WooSEO active_

<img width="681" alt="Screen Shot 2019-05-09 at 9 42 36 AM" src="https://user-images.githubusercontent.com/8238074/57458118-ca5ad500-723e-11e9-9e6e-9d964fb4876f.png">

_see a Yoast JSON+LD block with aggregateRating_
<img width="1267" alt="Screen Shot 2019-05-09 at 9 40 46 AM" src="https://user-images.githubusercontent.com/8238074/57458136-d2b31000-723e-11e9-9d71-9e969ee2b8ea.png">

**Comment by jono-alderson** [comment]
Have updated the docs.

**Comment by anasshaar** [comment]
Dear Gentlemen , 
Here is Anas who have this case . 

I would like to ask you is that working even when the aggregate rating and reviews collected by third party (Yotpo) ? currently aggregate rating not showing with yotpo . 

![YOSAT](https://user-images.githubusercontent.com/47484980/57597417-02705980-7558-11e9-9b83-b67c945ea0f1.png)

you can check the structure data test for the following product page https://fennec-fox.net/shop/playstation/

Best Regards 

Anas

**Comment by Pcosta88** [comment]
@jono-alderson I am confused. 

We say we output aggregateReview here https://developer.yoast.com/schema-documentation/woocommerce-seo/

<img width="776" alt="Screen Shot 2019-06-04 at 9 13 53 AM" src="https://user-images.githubusercontent.com/8238074/58881918-2fbcad00-86a9-11e9-8bde-c98ccf4af5e0.png">

Yet with Yoast SEO (free or premium), WooCommerce, and WooCommerce SEO we output aggregateRating in the WooCommerce block we take over

![Screen_Shot_2019-06-04_at_9_15_16_AM](https://user-images.githubusercontent.com/8238074/58882098-8924dc00-86a9-11e9-9367-e74b361d938c.jpg)

**Comment by jono-alderson** [comment]
Not sure I understand what the issue/question is, sorry.

**Comment by Pcosta88** [comment]
@jono-alderson Our documents for WooCommerce SEO state we output the aggregateReview:  https://developer.yoast.com/schema-documentation/woocommerce-seo/

However, when WooCommerce SEO is active, it fails to appear. _aggregateRating_ appears BUT not _aggregateReview_.

**Comment by jono-alderson** [comment]
Aha! So, `aggregateRating` is the correct property. `aggregateReview` is a typo in our documentation.
