### ISSUE TITLE
Add offerCount to AggregateOffer

### ISSUE THREAD

**Issue by jono-alderson** [Yoast/wpseo-woocommerce#372]
When an `AggregateOffer` exists (such as seen [here](https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Ffennec-fox.net%2Fshop%2Fplaystation%2F)), it should have an `offerCount` value.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 520203 when this conversation has been closed.

**Comment by jdevalk** [comment]
This has been fixed by WooCommerce, so it already works.
