### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'WPSEO_Schema_IDs' not found in woocommerce-schema.php

### ISSUE THREAD

**Issue by vverloop** [Yoast/wpseo-woocommerce#377]
### What did you expect to happen?
Loading good working Single Product Page in Woocommerce.

### What happened instead?
Singe Product Page in Wooocommerce breaks. Layout is messed up.
Error 500.
The problem occurs since the latest updates of Yoast SEO: WooCommerce / Yoast SEO Premium.

```
PHP message: PHP Fatal error:  Uncaught Error: Class 'WPSEO_Schema_IDs' not found in /home/xxxxx/domains/xxxxx.nl/public_html/wp-content/plugins/wpseo-woocommerce/classes/woocommerce-schema.php:98
Stack trace:
#0 /home/xxxxx/domains/xxxxx.nl/public_html/wp-includes/class-wp-hook.php(286): WPSEO_WooCommerce_Schema->change_product(Array, Object(WC_Product_Simple))
#1 /home/xxxxx/domains/xxxxx.nl/public_html/wp-includes/plugin.php(208): WP_Hook->apply_filters(Array, Array)
#2 /home/xxxxx/domains/xxxxx.nl/public_html/wp-content/plugins/woocommerce/includes/class-wc-structured-data.php(321): apply_filters('woocommerce_str...', Array, Object(WC_Product_Simple))
#3 /home/xxxxx/domains/xxxxx.nl/public_html/wp-includes/class-wp-hook.php(286): WC_Structured_Data->generate_product_data(Object(WC_Product_Simple))
#4 /home/xxxxx/domains/xxxxx.nl/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#5 /home/xxxxx/domains/xxxxx.nl/pub...
', referer: https://xxxxx.nl/shop/
```

### How can we reproduce this behavior?
Using the following software:
Theme: Yootheme Pro version: 1.20.6
Wordpress version: 5.2.1
Woocommerce version: 3.6.4
WooCommerce Brands version: 1.6.8
Yoast SEO Premium version: 11.3
Yoast SEO: Local version: 11.3
Yoast SEO: News version: 11.3
Yoast SEO: Video version: 11.3
Yoast SEO: WooCommerce version: 11.3

The problem occurs since the latest updates of Yoast SEO: WooCommerce / Yoast SEO Premium.

### Can you provide a link to a page which shows this issue?
No, because when i activate the Yoast SEO: WooCommerce plugin, my webshop breaks.
When i disable the plugin everything works fine.

### Technical info
* WordPress version: 5.2.1
* Yoast SEO version: 11.3

**Comment by Djennez** [comment]
Hi @vverloop and thank you for your report.

Have you checked for any [plugin conflicts](https://kb.yoast.com/kb/how-to-check-for-plugin-conflicts/)? Also: from what version of the plugin did you update to the 11.3 version?

**Comment by vverloop** [comment]
- I have disabled all the plugins except: Woocommerce, Woocommerce Brands, Yoast Premium & Yoast SEO Woocommerce.
- Enabled the default Wordpress theme: Twenty NineteenVersie: 1.4

Problem still exist after this test.

Yes i have updated to the 11.3 version.

**Comment by Djennez** [comment]
From what version did you upgrade tot the 11.3 version?

Do you have the complete error log available as well? The one in your post s cut short on some lines.

**Comment by vverloop** [comment]
I install v11.1 then update to v11.3.

**Comment by vverloop** [comment]
My test website: https://www.bookyourhotel.nl/bestemmingen/duitsland/berlijn/berlijn-berlijn/ao-berlin-friedrichshain-duitsland/

**Comment by vverloop** [comment]
https://www.bookyourhotel.nl/wp-content/debug.log

[04-Jun-2019 10:41:03 UTC] PHP Fatal error:  Uncaught Error: Class 'WPSEO_Schema_IDs' not found in /home/byh/domains/bookyourhotel.nl/public_html/wp-content/plugins/wpseo-woocommerce/classes/woocommerce-schema.php:98
Stack trace:
#0 /home/byh/domains/bookyourhotel.nl/public_html/wp-includes/class-wp-hook.php(286): WPSEO_WooCommerce_Schema->change_product(Array, Object(WC_Product_External))
#1 /home/byh/domains/bookyourhotel.nl/public_html/wp-includes/plugin.php(208): WP_Hook->apply_filters(Array, Array)
#2 /home/byh/domains/bookyourhotel.nl/public_html/wp-content/plugins/woocommerce/includes/class-wc-structured-data.php(321): apply_filters('woocommerce_str...', Array, Object(WC_Product_External))
#3 /home/byh/domains/bookyourhotel.nl/public_html/wp-includes/class-wp-hook.php(286): WC_Structured_Data->generate_product_data(Object(WC_Product_External))
#4 /home/byh/domains/bookyourhotel.nl/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#5 /home/byh/domains/bookyourhotel.nl/public_html/wp-includes/plugin.php(465): WP_Ho in /home/byh/domains/bookyourhotel.nl/public_html/wp-content/plugins/wpseo-woocommerce/classes/woocommerce-schema.php on line 98
[04-Jun-2019 10:41:46 UTC] PHP Fatal error:  Uncaught Error: Class 'WPSEO_Schema_IDs' not found in /home/byh/domains/bookyourhotel.nl/public_html/wp-content/plugins/wpseo-woocommerce/classes/woocommerce-schema.php:98
Stack trace:
#0 /home/byh/domains/bookyourhotel.nl/public_html/wp-includes/class-wp-hook.php(286): WPSEO_WooCommerce_Schema->change_product(Array, Object(WC_Product_External))
#1 /home/byh/domains/bookyourhotel.nl/public_html/wp-includes/plugin.php(208): WP_Hook->apply_filters(Array, Array)
#2 /home/byh/domains/bookyourhotel.nl/public_html/wp-content/plugins/woocommerce/includes/class-wc-structured-data.php(321): apply_filters('woocommerce_str...', Array, Object(WC_Product_External))
#3 /home/byh/domains/bookyourhotel.nl/public_html/wp-includes/class-wp-hook.php(286): WC_Structured_Data->generate_product_data(Object(WC_Product_External))
#4 /home/byh/domains/bookyourhotel.nl/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#5 /home/byh/domains/bookyourhotel.nl/public_html/wp-includes/plugin.php(465): WP_Ho in /home/byh/domains/bookyourhotel.nl/public_html/wp-content/plugins/wpseo-woocommerce/classes/woocommerce-schema.php on line 98
[04-Jun-2019 10:41:59 UTC] PHP Fatal error:  Uncaught Error: Class 'WPSEO_Schema_IDs' not found in /home/byh/domains/bookyourhotel.nl/public_html/wp-content/plugins/wpseo-woocommerce/classes/woocommerce-schema.php:98
Stack trace:
#0 /home/byh/domains/bookyourhotel.nl/public_html/wp-includes/class-wp-hook.php(286): WPSEO_WooCommerce_Schema->change_product(Array, Object(WC_Product_External))
#1 /home/byh/domains/bookyourhotel.nl/public_html/wp-includes/plugin.php(208): WP_Hook->apply_filters(Array, Array)
#2 /home/byh/domains/bookyourhotel.nl/public_html/wp-content/plugins/woocommerce/includes/class-wc-structured-data.php(321): apply_filters('woocommerce_str...', Array, Object(WC_Product_External))
#3 /home/byh/domains/bookyourhotel.nl/public_html/wp-includes/class-wp-hook.php(286): WC_Structured_Data->generate_product_data(Object(WC_Product_External))
#4 /home/byh/domains/bookyourhotel.nl/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#5 /home/byh/domains/bookyourhotel.nl/public_html/wp-includes/plugin.php(465): WP_Ho in /home/byh/domains/bookyourhotel.nl/public_html/wp-content/plugins/wpseo-woocommerce/classes/woocommerce-schema.php on line 98

**Comment by Djennez** [comment]
Hmmm, I'm unable to reproduce the issue with this information. Since you indicate that you have Yoast Premium, I'd advice you to contact our support. They might be able to check a bit more on your site. You can just reply to one of the purchase e-mails to contact them directly. If they are not able to help you they will create a new issue with additional information for debugging, if needed.

**Comment by pierps** [comment]
Hi @vverloop,
did you solve this issue? If yes, how did you solve?

**Comment by vverloop** [comment]
I did not solve the problem. I don't use the plugin now.

**Comment by vverloop** [comment]
I think that i'm not the only one, it is a big issue, but i am not going to fix the problem of an internal employer. I was thinking...later no time for it.
Yoast SEO Woocommerce should talk to the Yoast Premium Team, that there is a big issue.

**Comment by vverloop** [comment]
Every plugin is use for Wordpress is from high quality. But this plugin breaks my sites Yoast SEO Woocommerce Team have to look further. Not closing tickets.

**Comment by pierps** [comment]
I agree.
At the moment I'm using Yoast Premium 11.x with SEO Woocommerce 10.x and i have no issues...

**Comment by Djennez** [comment]
Older / different versions of our plugin will not work correctly together. With the latest versions, and a normal WordPress installation, we were unable to replicate these errors. But these errors look like errors that will be present when different versions of our plugin and extensions are paired together.

Since this is not a valid bug report (it was not reproducible) and the OP indicated to own the premium plugin, I would suggest contacting our support to get to the bottom of this.

**Comment by truchosky** [comment]
look the error on google, a lot of sites has it 
![imagen](https://user-images.githubusercontent.com/9977546/60379660-be042480-9a04-11e9-9985-e722a423ab43.png)

i have v 11.5 in yoast seo and seo woocommerce
