### ISSUE TITLE
WPSEO_Schema_IDs  doesn't exist on yoast premium

### ISSUE THREAD

**Issue by truchosky** [Yoast/wpseo-woocommerce#385]
### What did you expect to happen?
product page with out error

### What happened instead?
broken product site page

### How can we reproduce this behavior?
yoast seo premium + wp seo wocommerce both 11.5

### Can you provide a link to a page which shows this issue?
no, product page is broken, until deactivate wp seo woocommerce

### Technical info
* WordPress version: 5.2.2
* Yoast SEO version: 11.5
* wp seo woocomerce: 11.5

the problem was already posted in here, besides since yoast support doesnt answer I create a topic here

error is: `PHP message: PHP Fatal error:  Uncaught Error: Class 'WPSEO_Schema_IDs' not found in .../wp-content/plugins/wpseo-woocommerce/classes/woocommerce-schema.php:98`

the problem is yoast seo premium, if I use yoast seo free all work fine.

yoast free has class WPSEO_Schema_IDs in wpseo/fronted/schema/ thats why seo wocommerce plugin works with yoast free.

yoast premium hasn't WPSEO_Schema_IDs class in any file, it doesn't exist, thats why the error, yoast premium hasn't folder schema, has instead class-json-ld.php in frontend, how and why wpseo-woocommerce call to a class that doesn't exist in yoast premium?

**Comment by Djennez** [comment]
Premium does have the class `WPSEO_Schema_IDs`, but only since march 2019. Make sure you download the latest version of the premium plugin from https://my.yoast.com and install it on your site. It's best to remove the previous version of the premium plugin first. Please let me know once you've done this, as that should fix the problem.

**Comment by truchosky** [comment]
what yoast seo premium folder does contain WPSEO_Schema_IDs ?

**Comment by Djennez** [comment]
The same as in free.

**Comment by truchosky** [comment]
is not,the auto loader doesnt referece any wpseo_scheme class neither

**Comment by Djennez** [comment]
In that case you don't have an up to date, or an altered, version of the plugin at your disposal.

Have you reinstalled the plugin(s) downloaded from my.yoast.com as per earlier suggestion?

**Comment by Djennez** [comment]
Fixed by updating, according to https://github.com/Yoast/wpseo-woocommerce/issues/391 .
