### ISSUE TITLE
Replace Woo schema output

### ISSUE THREAD

**Issue by jono-alderson** [Yoast/wpseo-woocommerce#388]
At the moment, we programmatically alter the output of Woo's schema output to inject/modify our own values.

In order to minimise the risk of conflicts, and to increase the ease of integration/extension, I propose that we:

- Completely disable Woo's schema output.
- Retrieve Woo variables as required.
- Construct/modify our own graph in a manner consistent with our broader approaches.

cc @Xyfi

**Comment by truchosky** [comment]
wait a second, then this issue https://github.com/Yoast/wpseo-woocommerce/issues/385 is for that problem ?

**Comment by jdevalk** [comment]
Not going to do this as Woo seems to maintain theirs pretty nicely.
