### ISSUE TITLE
yoast seo woocommerce 11.6 and google structured data tool

### ISSUE THREAD

**Issue by truchosky** [Yoast/wpseo-woocommerce#391]
### What did you expect to happen?
show breadcrumb structured data on product
### What happened instead?
nothing, is the same activate or deactivate plugin
### How can we reproduce this behavior?
use yoast 11.6 and yoast seo woocommerce 11.6

### Technical info
* WordPress version: 5.2.2
* Yoast SEO version: 11.6 both, yoast and woocomerce yoast

Yoast seo woocommerce 11.6 doesnt add the breadcrumb structure to product page, this is my first time using yoast seo woocommerce with out error (check page https://github.com/Yoast/wpseo-woocommerce/issues/385), suddenly after update to 11.6 error was fixed but there is no change at all on product page, this example works, https://yoast.com/wordpress/plugins/seo/

![imagen](https://user-images.githubusercontent.com/9977546/61481074-4a02cf80-a965-11e9-8aed-8d578c9be092.png)

any ideas?

**Comment by Djennez** [comment]
Have you followed [this guide](https://kb.yoast.com/kb/replace-woothemes-breadcrumbs-by-yoast-breadcrumbs/)?

**Comment by truchosky** [comment]
support sucks, thx anyways, I will ask for a refund
