### ISSUE TITLE
WooCommerce Shop Base page in Products XML sitemap

### ISSUE THREAD

**Issue by Willem-Siebe** [Yoast/wpseo-woocommerce#401]
Hi,

In WooCommerce I have chosen to use the homepage as the shoppage.

When I look in my products xml sitemap, the shoppage is listed there as well, see below image, this is no good because that URL should not be indexed at all!

![1-1-2014 23-10-15](https://f.cloud.github.com/assets/5107354/1830276/aabc030c-7331-11e3-885d-b54b9fc783da.png)

What to do?

Kind regards,

Willem

**Comment by rmarcano** [comment]
As a temporary workaround, the filter [here](https://github.com/Yoast/wordpress-seo/issues/7002#issuecomment-299869724) should work.

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 531350 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 537962 when this conversation has been closed.

**Comment by galbaras** [comment]
So this was opened at the start of 2014!

I have a shop page that's set to "noindex", yet it features at the top of the Products XML sitemap.

Since there is a filter for excluding archive pages from CPT sitemaps, it should be an easy enough to make it a setting. One global setting will be good for me, but it may be better to add it to every taxonomy/CPT.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 556519 when this conversation has been closed.

**Comment by stodorovic** [comment]
Sorry for the delay. There is already PR #436 which fixes the issue related to "noindex". It will remove "shop page" form both sitemaps (if it's set to "noindex").

@Djennez @jono-alderson My opinion is that "shop page" should have same "behavior" as "posts page" (look Yoast SEO PR 11616). Regarding that "posts page" is removed from page sitemap if it's post archive, we should implement something like this. So, if "shop page" is set in WooCommerce then we should add its ID to _wpseo_exclude_from_sitemap_by_post_ids_.

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 569713 when this conversation has been closed.

**Comment by jdevalk** [comment]
@stodorovic your bugfix partially fixed this, what else is needed? :)

**Comment by jdevalk** [comment]
> My opinion is that "shop page" should have same "behavior" as "posts page" (look Yoast SEO PR 11616). Regarding that "posts page" is removed from page sitemap if it's post archive, we should implement something like this. So, if "shop page" is set in WooCommerce then we should add its ID to wpseo_exclude_from_sitemap_by_post_ids.

Honestly, it being linked from two XML sitemaps is probably a _good_ idea.

I've implemented your `-1` suggestion for when the shop page isn't set in #463

**Comment by stodorovic** [comment]
It looks good for me. I think that we could close this issue after merging PR #463.

I see other minor issues/possible optimizations, but it isn't directly related to this issue and I'll open new issue when I find out more details.

**Comment by galbaras** [comment]
> Honestly, it being linked from two XML sitemaps is probably a _good_ idea.

@jdevalk On one of my sites, I excluded the shop page from indexing, but it kept appearing in the product sitemap, and that's definitely NOT a good thing.

I'm confused as to what's been implemented. Can you please confirm the final outcome?

**Comment by stodorovic** [comment]
@galbaras No worry, PR #436  synchronizes behavior between page and product sitemap. If you set shop page to _noindex_ then it'll be excluded from both sitemaps.

Only minor concern is related to duplicated URL in page sitemap. I was thinking to exclude it from page sitemap if it's shown in product sitemap. It's more "cosmetics".
