### ISSUE TITLE
Support GTIN schema (UPC/EAN/ISBN/MPN)

### ISSUE THREAD

**Issue by acal** [Yoast/wpseo-woocommerce#416]
Yoast for Woocommerce plugin should provide configurations to either dynamically port the existing product SKU into a schema GTIN or provide a product-specific input field to manually set a product's GTIN. Both use cases would be great as there are cases where SKU and GTIN match and there are cases where they are different. 

This is so that we can appease the requirements for Google Search Console indexing so this feature would be super helpful. Thanks.

https://schema.org/gtin

**Comment by jlcox5** [comment]
This would be great!

**Comment by truchosky** [comment]
+ 10000
