### ISSUE TITLE
Review authors should reference complete objects

### ISSUE THREAD

**Issue by jono-alderson** [Yoast/wpseo-woocommerce#417]
We currently construct an `author` property for each `review` of a product. 

At the moment, that's constructed 'on the fly' and only populates the `type` and `name` properties based on the content/properties of the review; e.g., `"author":"@type":"Person","name":"Jono"}`.

When we know knowledge of the commenter, we should attempt to generate a top-level `Person` piece. The `author` property should reference this by ID.

If we have no knowledge of the author (i.e., an anonymous user entered a name and a comment), or if we can't generate a valid Person (e.g., we're missing a required attribute), the current approach should be used as a fallback.

See https://developer.yoast.com/features/schema/pieces/person/ for spec.

**Comment by jdevalk** [comment]
We currently rely on Woo's own output, which consist of the reviewers name only, I think this has limited added benefit for a ton of work, so I'm actually in favor of not doing this.
