### ISSUE TITLE
WooCommerce hasn't been tested notification

### ISSUE THREAD

**Issue by sannevndrmeulen** [Yoast/wpseo-woocommerce#434]
There's a new version available for WooCommerce (3.8). Right now I'm getting a notification when I navigate to **Plugins** (see image). This line `* WC tested up to: 3.7` in _wpseo-woocommerce.php_ should be updated.

<img width="1020" alt="Schermafbeelding 2019-11-06 om 10 10 32" src="https://user-images.githubusercontent.com/52161083/68285895-69427b80-0080-11ea-941c-e82d15b73eb0.png">

**Comment by jdevalk** [comment]
Technically this is not a regression, Woo has just released a new version.
