### ISSUE TITLE
Replace the helpscout beacon.

### ISSUE THREAD

**Issue by herregroen** [Yoast/wpseo-woocommerce#438]
Roadmap issue: https://github.com/Yoast/roadmap/issues/123
Product owners: @jdevalk @JessieHenkes 

Support for legacy Beacons will be coming to an end on December 5, 2019. 

We need to make sure we update our helpscout beacon before that time.

The following needs to be done:
- [x] The `wp-helpscout` library should be fully removed.
- [x] `classes/woocommerce-beacon-setting.php` should be removed.
- [x] The `init_beacon` should be rewritten to only load the updated beacon. It should still be active on the same pages. Use the integration from https://github.com/Yoast/wordpress-seo/issues/13864

**Comment by tacoverdo** [comment]
WooCommerce SEO beacon:
```
<script type="text/javascript">!function(e,t,n){function a(){var e=t.getElementsByTagName("script")[0],n=t.createElement("script");n.type="text/javascript",n.async=!0,n.src="https://beacon-v2.helpscout.net",e.parentNode.insertBefore(n,e)}if(e.Beacon=n=function(t,n,a){e.Beacon.readyQueue.push({method:t,options:n,data:a})},n.readyQueue=[],"complete"===t.readyState)return a();e.attachEvent?e.attachEvent("onload",a):e.addEventListener("load",a,!1)}(window,document,window.Beacon||function(){});</script>
<script type="text/javascript">window.Beacon('init', '8535d745-4e80-48b9-b211-087880aa857d')</script>
```
