### ISSUE TITLE
[Feature Request] Enhancements to product meta tags for Facebook Catalog

### ISSUE THREAD

**Issue by jono-alderson** [Yoast/wpseo-woocommerce#456]
Facebook Catalog (the product feed system which powers Facebook Marketplace) is able to extract open graph / schema data from a page in order to automatically populate or update a store's inventory.

Our current meta tags require only a few tweaks in order to make them compatible with this feature.

## Requirements

We should do the following on product templates:
- Add a `<meta property="product:retailer_item_id" content="{{SKU}}" />` tag, where `{{SKU}}` is the product SKU.
- Add a `<meta property="product:brand" content="{{BRAND_NAME}}" />` tag, where `{{BRAND_NAME}}`.
- Alter the value of the `product:availability` tag from `instock` to `in stock`.

## Future considerations
We should also support a `<meta property="product:category" content="{{CATEGORY}}" />` tag. However, this will require some UI work - the tag value must be one of the values [from here](https://www.google.com/basepages/producttype/taxonomy.en-US.txt), which would necessitate a selector interface.

That's outside the scope of this ticket, but worth being aware of.

**Comment by jono-alderson** [comment]
Note that the current `product:availability` value of `instock` is technically a bug.

**Comment by jdevalk** [comment]
BRAND is already an option, based on what you set as the brand taxonomy in the settings.
