### ISSUE TITLE
WooCommerce 12.5 generates a console log error

### ISSUE THREAD

**Issue by sannevndrmeulen** [Yoast/wpseo-woocommerce#491]
While testing Yoast SEO: WooCommerce 12.5-RC2 I've run into an error on the Products page for WooCommerce. The error mentions our previous version, 12.4.1.

### How can we reproduce this behaviour?
1. With WooCommerce 3.9.0, Yoast SEO 13.0-RC1, and Yoast SEO: WooCommerce 12.5-RC2 active
2. When you navigate to the WooCommerce Products page
3. You'll see this error in the console log:
<img width="390" alt="Schermafbeelding 2020-01-22 om 14 52 02" src="https://user-images.githubusercontent.com/52161083/72903102-ea7ae780-3d2c-11ea-812a-83509c615f50.png">

**Comment by hansjovis** [comment]
Fixed in https://github.com/Yoast/wpseo-woocommerce/pull/493.

**Comment by dariaknl** [comment]
The error is reproduced after the fix:
<img width="1035" alt="Screenshot 2020-01-27 at 15 22 13" src="https://user-images.githubusercontent.com/19681708/73182730-da427e00-4119-11ea-8db7-e4cf1d4bc560.png">

**Comment by dariaknl** [comment]
fixed in RC3.
