### ISSUE TITLE
New GTIN, ISBN and MPN fields cannot be changed

### ISSUE THREAD

**Issue by dariaknl** [Yoast/wpseo-woocommerce#495]
### How can we reproduce this behavior?
1. Install and activate Yoast SEO 13.0 RC1.
2. Install and activate Yoast SEO: WooCommerce 12.5 RC3.
3. Install and activate WooCommerce 3.9.0.
4. Go to create new product, add title, price and in new Yoast SEO product data tab add GTIN8:
<img width="614" alt="Screenshot 2020-01-28 at 08 21 51" src="https://user-images.githubusercontent.com/19681708/73243188-47e8bb80-41a7-11ea-9c98-b45496d9dffb.png">

5. Publish product. 
6. Go to edit product once again, empty GTIN8 field, update product.
7. Refresh page and check that field is not empty:
<img width="408" alt="Screenshot 2020-01-28 at 08 23 03" src="https://user-images.githubusercontent.com/19681708/73243259-72d30f80-41a7-11ea-8de7-3a3d5acd2473.png">

The same is reproduced for all new fields in Yoast SEO product data tab.

**Comment by jdevalk** [comment]
Correction: it can be _changed_ it cannot be _emptied_. Fixing.

**Comment by jdevalk** [comment]
Fixed by #503
