### ISSUE TITLE
Empty retailer_item_id output on empty SKU

### ISSUE THREAD

**Issue by Djennez** [Yoast/wpseo-woocommerce#496]
### What did you expect to happen?

When a product SKU is not set, its metadata to not be output on the product page.

### What happened instead?

An empty SKU will show `<meta property="product:retailer_item_id" content="" />` in the page code.

### How can we reproduce this behavior?

1. Create a product in WooCommerce
2. Do not fill out the SKU
3. Check the product page and see the corresponding header with an empty `content` field.

Can you provide a link to a page which shows this issue?

### Technical info
* WordPress version: 5.3.2
* Yoast SEO version: 12.9 Premium + WooCommerce SEO 12.5-RC3

**Comment by dariaknl** [comment]
Small update: when you fill SKU in product Inventory, then `product:retailer_item_id` is filled in:
<img width="807" alt="Screenshot 2020-01-28 at 10 43 56" src="https://user-images.githubusercontent.com/19681708/73256227-d702cd00-41c1-11ea-9b04-5f7e8cc6911a.png">

**Comment by jdevalk** [comment]
Fixed by #504
