### ISSUE TITLE
Structured data: seller defaults to organization 

### ISSUE THREAD

**Issue by Djennez** [Yoast/wpseo-woocommerce#497]
### What did you expect to happen?
When my website is set to represent a person, I expect the seller of a product in WooCommerce to not be an organisation.

### What happened instead?
The plugin forces the seller in the structured data to be an organization, even if the website is set to represent a person:

```
                    "seller": {
                        "@type": "Organization",
                        "name": "Yoast acceptance WP site",
                        "url": "http://acceptance.test"
                    },
```

### How can we reproduce this behavior?

1. Set your website to represent a person and not an organization in SEO -> Search Appearance
2. Check the page source of a product and see the respective structured data output under `seller`

### Possible fix
Local SEO forces the representation of a website to be an organization. Perhaps the core plugin should have a clear filter that would allow other plugins to force an organization as well. This way we can streamline this behavior and make it more consistent.

### Technical info
* WordPress version: 5.3.2
* Yoast SEO version: 12.9 Premium + WooCommerce SEO 12.5-RC3

**Comment by jdevalk** [comment]
This is by design, as the seller can't be a person according to Google.
