### ISSUE TITLE
productID shown when SKU filled in

### ISSUE THREAD

**Issue by dariaknl** [Yoast/wpseo-woocommerce#498]
### How can we reproduce this behavior?
1. Install and activate Yoast SEO 13.0 RC1.
2. Install and activate Yoast SEO: WooCommerce 12.5 RC3.
3. Install and activate WooCommerce 3.9.0.
4. Go to create new product, add title and price.
5. Publish product and grab schema - `productID` is not shown.
According to https://github.com/Yoast/wpseo-woocommerce/pull/460 `productID` should be output.

6. Go to edit product once again, add SKU in Inventory:
<img width="807" alt="Screenshot 2020-01-28 at 10 43 56" src="https://user-images.githubusercontent.com/19681708/73252503-21cd1680-41bb-11ea-9cbe-48b89d5f6fa7.png">

7. Update product and grab schema - `productID` is shown:
<img width="857" alt="Screenshot 2020-01-28 at 10 45 03" src="https://user-images.githubusercontent.com/19681708/73252620-4de89780-41bb-11ea-8121-6df2a9670f2d.png">

**Comment by jono-alderson** [comment]
We're planning to remove the `productID` attribute - see https://github.com/Yoast/wpseo-woocommerce/issues/500

**Comment by dariaknl** [comment]
fixed in #505
