### ISSUE TITLE
Inconsistency in offer and review ids

### ISSUE THREAD

**Issue by dariaknl** [Yoast/wpseo-woocommerce#499]
### How can we reproduce this behavior?
1. Install and activate Yoast SEO 13.0 RC1.
2. Install and activate Yoast SEO: WooCommerce 12.5 RC3.
3. Install and activate WooCommerce 3.9.0.
4. Go to create new product, add title and price.
5. Publish product and add reviews.
6. Grab the whole schema and check the output:

Offer and review `ids` which are introduced here https://github.com/Yoast/wpseo-woocommerce/pull/468 and https://github.com/Yoast/wpseo-woocommerce/pull/465 are based on productID which is also output in SKU (614). 
<img width="662" alt="Screenshot 2020-01-28 at 13 41 49" src="https://user-images.githubusercontent.com/19681708/73265292-f6efbc00-41d4-11ea-801a-c3b531502498.png">

<img width="658" alt="Screenshot 2020-01-28 at 13 41 39" src="https://user-images.githubusercontent.com/19681708/73265218-c4de5a00-41d4-11ea-9473-96ee4a9019ed.png">

But you can also overwrite SKU by setting new value in product Inventory:
<img width="576" alt="Screenshot 2020-01-28 at 13 43 58" src="https://user-images.githubusercontent.com/19681708/73265334-0b33b900-41d5-11ea-9aad-f21c200f7159.png">

When you update the product and check schema, then you see the following:
<img width="652" alt="Screenshot 2020-01-28 at 13 50 53" src="https://user-images.githubusercontent.com/19681708/73265422-3c13ee00-41d5-11ea-932b-6de713bbeffa.png">

<img width="673" alt="Screenshot 2020-01-28 at 13 51 00" src="https://user-images.githubusercontent.com/19681708/73265430-3fa77500-41d5-11ea-9d1b-8f1021341a56.png">

SKU and productID are updated from 614 to "hahahah" but offer and review `ids` are still pointing to the old one - 614.
This behaviour seems inconsistent.

**Comment by jdevalk** [comment]
It's inconsistent but doesn't matter :)
