### ISSUE TITLE
Handle the permalink saves of WooCommerce fields.

### ISSUE THREAD

**Issue by andizer** [Yoast/wpseo-woocommerce#501]
We should listen to the option change of `woocommerce_permalinks` and then reset the permalinks for the things that got changed. This need some calculation of difference between the old and new option value. 

Also to integrate fully with https://github.com/Yoast/wordpress-seo/pull/14275 we have to remove the product from the post types array:
```php
\add_filters( 'wpseo_post_types', function( $post_types, $context ) {
   if ( $context === 'update_permalink' ) {
       unset( $post_types['product'] ); 
   }

   return $post_types;
 }, 10, 2 );
```

~We should find a way to make `reset_permalink_indexables` reusable or maybe~ be straight forward and copy the method to the class we make for this pull request.

## To do
- [x] Listen to the option change of `woocommerce_permalinks`
- [x] Check if option has changed: 
   - [x] Reset the permalinks if there is an option change (depending on what value has changed).
- [x] Remove the product from the post types array
- [ ] Write tests

**Comment by johannadevos** [comment]
For inspiration for comparing the old and new option value, see `src/integrations/watchers/indexable-post-type-archive-watcher.php` (renamed to `src/integrations/watchers/wpseo-titles-option-watcher.php` and extended in [this PR](https://github.com/Yoast/wordpress-seo/pull/14317)).

**Comment by johannadevos** [comment]
In the PR I mentioned above I made a function for this: `has_option_value_changed`.

**Comment by IreneStr** [comment]
More inspiration: https://github.com/Yoast/wordpress-seo/issues/13800

**Comment by hansjovis** [comment]
Fixed in https://github.com/Yoast/wpseo-woocommerce/pull/525
