### ISSUE TITLE
Taxonomies removed from sitemaps, why?

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/wpseo-woocommerce#51]
When activating WooCommerce SEO, some taxonomies are removed from the XML sitemaps. There is no option to filter the taxonomies that are removed. Why are the taxonomies removed and should we add the option to filter that?

**Example taxonomy**
![gender_ _toys_in_a_hurry_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/5535647/93a62b24-8a83-11e4-8587-b7104556ca1f.png)

**Even though the pa_XXXX taxonomies are filtered from the sitemaps, they still show up in the 'Exclude'-list.**
![xml_sitemaps_-_yoast_wordpress_seo__ _toys_in_a_hurry_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/5535652/9d064014-8a83-11e4-90ec-f507308a64e5.png)

**The actual sitemaps**
![xml_sitemap](https://cloud.githubusercontent.com/assets/5147598/5535660/ba099f58-8a83-11e4-8db9-b0471d92b368.png)

**Comment by moorscode** [comment]
As this has not resulted in any questions or problems, and this issue is as old as it is, I'm closing it.
