### ISSUE TITLE
Sale price, regular price and priceValidUntil

### ISSUE THREAD

**Issue by galbaras** [Yoast/wpseo-woocommerce#526]
### What did you expect to happen?
Sales normally have a validity period, so there should be a field for it in products/variations.

When a product is on sale, its schema markup should include both the regular price and the sale price, similar to Google's specifications for product feeds.

### What happened instead?
priceValidUntil was just removed from the plugin, and only a single price appears in the markeup.

Google Search Console issues warnings to sites since v12.5 due the removed attribute.

### How can we reproduce this behavior?
Set a sale price for a product and check the schema markup on the product page.

### Can you provide a link to a page which shows this issue?

https://dev.get-business-online.com/pacificsprings/product/urbane-spring-water-cooler/

### Technical info
* WordPress version: 5.3.2
* Yoast SEO version: 13.0
* Yoast SEO for WooCommerce version: 12.5.1

**Comment by Flobaby** [comment]
Thanks for starting this thread. Yep, Google is giving me validation problems for priceValidUntil. Just to add my 2 cents. :)

**Comment by cavalierlife** [comment]
+1 . Please undo the change made in the latest version. Two days ago I posted the following in the wp.org support forum. Will repost here:

Yesterday’s Yoast changelog includes: “Removes the priceValidUntil attribute, as it’s not sensible.”

_Today, my client gets an email from Google that says

Search Console has identified that your site is affected by 1 Products issues:

Top Warnings

Warnings are suggestions for improvement. Some warnings can affect your appearance on Search; some might be reclassified as errors in the future. The following warnings were found on your site:

Missing field “priceValidUntil”

We recommend that you fix these issues when possible to enable the best experience and coverage in Google Search._

So I’m thinking maybe Google thinks it was sensible. Waiting for my client to call me in a panic….

**Comment by Djennez** [comment]
Hmm, it's a bug that we don't show the `priceValidUntil` on (scheduled) sale products. So I'll mark this as bug specifically for that case. It is, however, intentional to not show this value on every product page, as it makes no sense on products that have a fixed price.

**Comment by galbaras** [comment]
Thanks.

I think the removal could have been documented better. Reference to "regular price" would have made sense to everyone, I'm sure, especially after sale prices get the attribute back.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 582990 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 583176 when this conversation has been closed.

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 586319 when this conversation has been closed.

**Comment by galbaras** [comment]
I was really hoping to see that this has been closed in 12.6 :(

**Comment by afercia** [comment]
Looking at what Woo does, all products _including the ones on sale_ get a `priceValidUntil` date defaulting to last day of next year e.g. `2021-12-31`.

Given that, please clarify when a `priceValidUntil` property should be output:
- The product is on sale regardless of whether the sale price dates were set. In this case:
  - if users didn't explicitly set the sale price dates values, `priceValidUntil` will default to `2021-12-31`
  - if they did, `priceValidUntil` will output the "To" date
- The product is on sale _and_ users explicitly set the sale price dates. In this case:
  - if users didn't explicitly set the sale price dates values, `priceValidUntil` won't be output 
  - if they did, `priceValidUntil` will output the "To" date

/Cc @jono-alderson

**Comment by jono-alderson** [comment]
The second approach - only when it's on sale, and we have an explicit.

**Comment by galbaras** [comment]
@jono-alderson This will not prevent Google from issuing warnings about product schema, unfortunately. Are you guys communicating with them about this? After all, the main concern here is losing ranking points.

**Comment by jono-alderson** [comment]
The warnings don't harm performance. We'd also like Google to make this more clear in their testing tools and documentation! :(

**Comment by galbaras** [comment]
A change has been merged into trunk. Why is this issue still open? Can I help with anything?

**Comment by afercia** [comment]
@galbaras thank you for all your feedback and dedication to this issue 🙂 No changes have been merged yet though. This issue will be closed as soon as https://github.com/Yoast/wpseo-woocommerce/pull/530 goes through our code review / acceptance process and merged.

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 589326 when this conversation has been closed.

**Comment by truchosky** [comment]
still warning, is not a fix for that?

**Comment by Jesseadamwilson** [comment]
I'm experiencing the same issue as discussed here in this thread and also this conversation here: https://wordpress.org/support/topic/google-warning-about-pricevaliduntil/

Is there a fix? I have the Yoast WooCommerce add-on installed and I am still receiving error Missing field "priceValidUntil" in Google Search Console. Please advise.

**Comment by Pcosta88** [comment]
@JesserH 

Hi, we understand you have our WooCommerce SEO add on plugin. We are happy to help resolve this issue. We ask that you please send us an email to support@yoast.com help. That way we can review the account and settings to help resolve the issue.

**Comment by ilgraziano** [comment]
hi. i still have the same problem. i contacted yoast support and this is the reply about this problem:
"The priceValidUntil field was removed in version 12.5 of the WooCommerce SEO plugin because it automatically included a default date, which did not make sense unless you add sale price dates in the WooCommerce product data. Our development teams are already working on an improvement for this. Unfortunately, we don't have an exact date for its release."

Is there any other way to solve or bypass the warning waiting for the patch?
thnx

**Comment by galbaras** [comment]
Yes, I still have this issue too. Simply removing the default was not a good thing. Some sales have no known end date, e.g. "while stocks last" and setting/updating dates can be a hassle in a big shop.

This is not the only time the Yoast team took this type of liberty, which resulted in Google notices. May I suggest more community consultation, particularly for a paid product?

**Comment by JesserH** [comment]
@galbaras I will take a closer look into this next Friday

**Comment by jono-alderson** [comment]
Lots of moving parts here, so please accept my apologies if I miss anything. I think this is where we're at...

**On `priceValidUntil` values:**
- Historically, Yoast output a default `priceValidUntil` property on all `offer` schema pieces, with an (arbitrary) value of one year in the future. This was done to prevent warnings in Google's Structured Data Testing Tool (SDTT).
- We made a product decision to remove that value, as setting an invalid end date could cause problems (e.g., misrepresenting product prices/durations can have SEO and even legal repercussions). In almost all cases, prices are valid 'indefinitely'; they're the price they are until they're not, and don't have an 'end date'.
- More broadly, it's our opinion that we shouldn't output knowingly incorrect values in schema markup for the sake of appeasing the SDTT, which does a poor job of differentiating between 'errors' and 'warnings' (both technically, and in its communications).
- However, when a product is on sale, and that sale has an end date, we add a `priceValidUntil` value into the `offer`.

**On representing the sale price vs the normal price:**
- I firmly agree with the following, in principle:
  > When a product is on sale, its schema markup should include both the regular price and the sale price, similar to Google's specifications for product feeds.
* However, there is no supported mechanism for doing this with/for Google. Whilst there are schema properties which describe the start and end period of availability (with some nuance), Google doesn't support/use these properties, and including them causes undesirable behaviour (Google shows a 'price range' result).
* We're hoping that the upcoming enhancements schema.org's product grouping and definitions comes with a better way to handle this, which is, indeed, more closely in line with how their product feeds behave.

**Comment by jono-alderson** [comment]
As such, I think that we can safely keep this issue closed. It's muddy, but I think that the decisions we've made are sensible, and the best solution to an imperfect situation.

**Comment by jono-alderson** [comment]
And of course, for anybody who disagrees, you're welcome to use our API (https://developer.yoast.com/features/schema/api/) to customize your setup. I'd love to see some examples of edge-cases in the wild.

**Comment by galbaras** [comment]
Thank for the clarifications, @jono-alderson . I'd love to use the Schema API, but struggle to find examples for this. Would you be so kind as to suggest sample code for setting the `priceValidUntil` property of a product?

**Comment by jono-alderson** [comment]
Happy to help!

There's a section in our documentation about changing a graph piece's data - see https://developer.yoast.com/features/schema/api/#change-a-graph-pieces-data.

If you adapt this to `wpseo_schema_offer` (note that `priceValidUntil` is a property of the `offer`, not the `product`), then you can add your own logic in the related function to determine what changes you want to make to which offer, in which circumstances.

E.g.,
```
## Adds a priceValidUntil value to all offers
add_filter( 'wpseo_schema_offer', 'example_change_offer' );
function example_change_offer( $data ) {
    $data['priceValidUntil'] = '2025-12-31';
    return $data;
}
```

Bear with me, though; that doesn't appear to be working on our side. Investigating!

**Comment by galbaras** [comment]
Any news?

Is it possible that being a sub-type, the filter name is different, e.g. `wpseo_schema_product` (with more complex code)?

**Comment by jono-alderson** [comment]
It looks like our filters don't alter the WooCommerce schema, because it outputs in a separate graph (in the footer of the page).
I've opened an internal ticket for us to look at this, but can't promise that it'll happen immediately. I'll keep you in the loop, though!

**Comment by jono-alderson** [comment]
While we're looking into this, you could use WooCommerce's own filtering solution as a temporary patch.
Something like the following should do the trick!
 
```
add_filter( 'woocommerce_structured_data_product', 'example_change_product', 10, 2 );
function example_change_product( $markup, $product ) {
  if ( is_product() ) {
    // Make arbitrary changes here
  }
  return $markup;
}
```

**Comment by galbaras** [comment]
This didn't work the last time I tried, because the Yoast plugin removes it completely

**Comment by galbaras** [comment]
This issue isn't resolved and shouldn't be closed.

@jono-alderson can you offer working code, please?

**Comment by galbaras** [comment]
@jono-alderson is it on the team's radar that the filter isn't working? The function `change_product()` (see [here](change_product)) recreates the markup from scratch and offers no Yoast-specific filters, so the WC filter has no effect. Then, as you say, the filter `wpseo_schema_offer` has no effect either.

I need a way to modify the output. Please provide.

**Comment by jono-alderson** [comment]
Hello,

I'm sorry that you're struggling with this; I appreciate that it's frustrating that our filters don't work here.
I've added the fix to our internal backlog, and it's on our radar. I'm hoping that we'll be able to provide you with an update and a solution soon!

**Comment by galbaras** [comment]
@jono-alderson I see that the idea from @njeffers was not adopted, despite being simple and direct, but markup is now filterable.

How would I use a filter to revert `priceValidUntil` to its previous value, as computed by WooCommerce?

**Comment by galbaras** [comment]
Also, the `wpseo_schema_product` filter should also take a second argument of `$product`, which is available in the context and will likely be required for proper filtering.

This issue should be reopened pending full implementation.

**Comment by jono-alderson** [comment]
Hi @galbaras,

You can retrieve and work with the global $product variable, and test it against whatever business/product logic you need; e.g.,

```
function example_change_product( $data ) {
	// Get the product var.
	global $product;

	// Check if we should set a priceValidUntil value.
	if ( ! example_conditions_func( $product ) ) {
		return $data;
	}

	// Get a priceValidUntil value.
	$valid_until = example_valid_until_func( $product );
	if ( ! $valid_until ) {
		return $data;
	}

	// Set the value.
	$data['priceValidUntil'] = $valid_until;
	return $data;
}
add_filter( 'wpseo_schema_product', 'example_change_product' );
```

**Comment by galbaras** [comment]
I think that the global `$product` is the parent. I also think that the field to change is the `['priceValidUntil']` element of each one of  `$data['offers']`.

Also, when reverting to the WooCommerce default value, I don't need the sale price, so `$product->is_on_sale()` will suffice. The rest is adding a year to "now".

It would be great if you could offer a tested solution, given the high visibility of Github issues.

Even greater would be the proposed @njeffers filter that simply stops your plugin from removing what's already there, although I'd rename it to `wpseo_schema_remove_price_valid_until`.

**Comment by hassankarami** [comment]
> If anyone's interested, this code adds the default validity date back into the offer:
> 
> ```
> add_filter( 'wpseo_schema_product', 'gbol_reset_price_valid_until' );
> function gbol_reset_price_valid_until( $data ) {
> 	global $product;
> 
> 	if ( ! empty( $data['offers'] ) ) {
> 		foreach ( $data['offers'] as $key => $offer ) {
> 			if ( ! isset( $offer['priceValidUntil'] ) && $product->is_on_sale() ) {
> 				$data['offers'][$key]['priceValidUntil'] = date( 'Y-12-31', time() + YEAR_IN_SECONDS );
> 			}
> 		}
> 	}
> 
> 	return $data;
> }
> ```

Will this code solve the warning problem?

**Comment by galbaras** [comment]
Only for items that have a sale price (`is_on_sale()`). However, Google seems to be expecting this everywhere, so to apply to all the products, just remove this: `&& $product->is_on_sale()`.

**Comment by Ceylanalkan** [comment]
I have that same problem  https://urfayoresi.com/urun/urfa-ev-yapimi-aci-biber-salcasi/

**Comment by RicardoRDS** [comment]
@galbaras thanks, your code works just perfect. The warning is gone.

**Comment by trentest** [comment]
> If anyone's interested, this code adds the default validity date back into the offer:
> 
> ```
> add_filter( 'wpseo_schema_product', 'gbol_reset_price_valid_until' );
> function gbol_reset_price_valid_until( $data ) {
> 	global $product;
> 
> 	if ( ! empty( $data['offers'] ) ) {
> 		foreach ( $data['offers'] as $key => $offer ) {
> 			if ( ! isset( $offer['priceValidUntil'] ) && $product->is_on_sale() ) {
> 				$data['offers'][$key]['priceValidUntil'] = date( 'Y-12-31', time() + YEAR_IN_SECONDS );
> 			}
> 		}
> 	}
> 
> 	return $data;
> }
> ```

@galbaras Apologies for silly question. This fix is to go into the functions.php or best at add with plugin like Code Snippets?

**Comment by galbaras** [comment]
> This fix is to go into the functions.php or best at add with plugin like Code Snippets?

It can go into functions.php, a Code Snippets entry or a custom plugin. Personally, I use functions.php, but if you ever switch themes, you'll have to add the snippet to the new functions.php, whereas the other options will simply continue to work.
