### ISSUE TITLE
Getting this error in search console

### ISSUE THREAD

**Issue by Flobaby** [Yoast/wpseo-woocommerce#527]
### What did you expect to happen? 
Yoast SEO Woocommerce plugin is supposed to alleviate this "“Either ‘offers’, ‘review’ or ‘aggregateRating’ should be specified”  according to this page https://yoast.com/search-console-showing-errors-in-your-product-structured-data/

### What happened instead? 
Was not a problem before but yesterday started getting numerous errors with “Either ‘offers’, ‘review’ or ‘aggregateRating’ should be specified”

### How can we reproduce this behavior? Not sure.

Can you provide a link to a page which shows this issue? 
It's telling me this link https://www.niftyprintables.com/product-category/graduation/page/1/?orderby=price-desc for example, but naming a particular item that is in that category. Image attached.
![Annotation 2020-02-09 132023](https://user-images.githubusercontent.com/60805325/74107517-fe9d5200-4b3e-11ea-8f52-d5fbfa3153b9.png)

### Technical info
* WordPress version: 5.3.2
* Yoast SEO version: 13.0
* Yoast SEO for WooCommerce version: 12.5.1

Thank you!
Flo

**Comment by Djennez** [comment]
Hi @Flobaby, this is a premium product support question and not a bug report. Please contact our support engineers, as they will gladly help you out with this question.
