### ISSUE TITLE
[Request] Add a developer filter to control whether schema includes tax.

### ISSUE THREAD

**Issue by dnusca** [Yoast/wpseo-woocommerce#542]
### What did you expect to happen?

The ability to choose whether the schema outputs the price and price offers including tax.

### What happened instead?

Since 12.6.1 the output of tax inclusive or exclusive is solely reliant on the the WooCommerce setting for displaying tax on shop pages and the option has been removed.

Google Shopping requires prices inclusive of tax for a majority of countries, however a lot of B2B stores rely on the WooCommerce setting to be 'exclusive'. Changing this WooCommerce setting not only affects the display but also searching via price in a products query.

I would ask if it's possible to allow a developer filter here for us to choose since the option is gone?

### How can we reproduce this behavior?

Install the latest version on Yoast and WooCommerce SEO.

Can you provide a link to a page which shows this issue?

### Technical info
* WordPress version: 5.3.2
* Yoast SEO version: 13.2
* Yoast SEO for WooCommerce version: 12.6.1

**Comment by Djennez** [comment]
Hi @dnusca and thanks for your request. We hook into the WooCommerce `woocommerce_structured_data_product` filter:

https://github.com/Yoast/wpseo-woocommerce/blob/1b0432563cf93bcc6b500331677a3af3741c01cc/classes/woocommerce-schema.php#L35

You could hook into the same filter and overwrite the changes that we made. We currently don't have a filter to change this behavior in our addon.

**Comment by dnusca** [comment]
Hi @Djennez, 

We'd still like to use all the other data you add to the product schema, we just want to display inclusive while our WC shop setting is exclusive.

I understand linking it to the WooCommerce setting eliminates the decision from your plugin, but would you be open to allowing a developer filter here since it was previously an option?

Thanks for your time and answers

**Comment by Djennez** [comment]
Yea, if you use the same filter on priority 11 or higher (so after our execution) you can change the same product details. 

If this solves your question, can this issue be closed?

**Comment by dnusca** [comment]
Perfect, closing the issue.

**Comment by dnusca** [comment]
Hi, so I have attempted this, however you return an empty array in your function so there is no data to edit at this point? Is this intentional?

https://github.com/Yoast/wpseo-woocommerce/blob/1b0432563cf93bcc6b500331677a3af3741c01cc/classes/woocommerce-schema.php#L133

**Comment by Djennez** [comment]
Hmmm I see. @jdevalk if you have the time, could you provide insight in how developers might hook into this?

**Comment by jdevalk** [comment]
Ah you're right @dnusca this one works differently from our other ones. We'll have to introduce a filter in the `output_schema_footer` function to be able to filter this. @Djennez can you make an issue for that?

**Comment by dnusca** [comment]
Thanks @jdevalk and @Djennez 

I will close this issue and track #547.
