### ISSUE TITLE
Yoast SEO WooCommerce does not play nicely with Elementor

### ISSUE THREAD

**Issue by bobmulder** [Yoast/wpseo-woocommerce#545]
### What did you expect to happen?

Hey there! I am using Elementor Pro (including the theme builder), in combination with WooCommerce, Yoast Premium and Yoast WooCommerce.

Thing is - as mentioned in my [issue at Elementor](https://github.com/elementor/elementor/issues/10748) - that Yoast WooCommerce hooks onto several actions (like `woocommerce_single_product_summary`), which are never executed by a custom template from Elementor.

Question to you is: where does this problem happen?

1. Elementor should use the hooks defined by WooCommerce to fulfill it's standards and integrations (like Yoast WooCommerce).

_or:_

2. Yoast WooCommerce should hook into different actions to not be restricted by visual builders like Elementor.

I'd like to know your point of view on this...

### What happened instead?

I'd like to refer to my issue here: https://github.com/elementor/elementor/issues/10748

### How can we reproduce this behavior?

I'd like to refer to my issue here: https://github.com/elementor/elementor/issues/10748

**Comment by Djennez** [comment]
In your setup, is there *any* woocommerce product schema at all?

**Comment by bobmulder** [comment]
I am sorry for the confusion Djennez, the following `@type`s are visible:
- `Website`
- `SearchAction`
- `ImageObject`
- `ItemPage`

As mentioned before, the `Product` type is missing

**Comment by Djennez** [comment]
In that case WooCommerce's complete schema functionality seems to be ignored by your CPT. This means that we can't hook into WooCommerce at all. So this is not an issue with WooCommerce SEO (or even WooCommerce I think). If the CPT is not loading the needed WooCommerce functions there is nothing we can do about this :)

**Comment by bobmulder** [comment]
That's what I thought, Djenniz, however I want to be sure this thought is right. I'll get back to Elementor (see my issue above) to see what they think about this.

Thank you for your attention!

**Comment by bobmulder** [comment]
@Djennez, as posted in elementor/elementor#10748, a temporary has been posted. 

The result by now is that I got a Yoast Schema Graph on the top of my HTML (head) with general schema's (which is done by Yoast Premium, not Yoast WooCommerce), and a got a second Yoast Schema Graph on the bottom of my HTML (body) with the product specific schema's (which is done by Yoast WooCommerce through my custom shortcode.

In my search for the right solution, the question I have for you: is this best practice / okay to have multiple schema blocks in your HTML as described above, or should this always be one schema block?

**Comment by Djennez** [comment]
@bobmulder without alterations, there would be 2 schema blocks on WooCommerce pages as well. One in the head (Yoast) and one near the footer (Yoast + WooCommerce). Our plugin links elements from these sections together so it is no problem that these are output in different places.

**Comment by bobmulder** [comment]
Thank you for your response @Djennez, it's all clear!

Sidenote: the Elementor team is investigating the issue I mentioned before, so I expect the Yoast WooCommerce plugin to work the right way soon.

**Comment by rmarcano** [comment]
The Elementor team suggested a filter that might fix this issue [here](https://github.com/elementor/elementor/issues/10748#issuecomment-598623002)

**Comment by bobmulder** [comment]
Nice how you are referencing to my comment @rmarcano while I opened both of this issues for the same issue 😆
