### ISSUE TITLE
Alterations to product availability meta/schema

### ISSUE THREAD

**Issue by jono-alderson** [Yoast/wpseo-woocommerce#555]
We need to make some improvements to the logic which determines which meta tags and schema values are output on Woo product pages, specifically relating to product _availability_. 

See https://developer.yoast.com/product-availability-woocommerce/ for further context.

### When a product is in stock
- Output a `og:availability` meta tag.

  E.g.. `<meta property="og:availability" content="instock" />`

### When a product is out of stock
- Add `product:availability` and `og:availability` meta tags, with a value of `out of stock`.

  E.g.. `<meta property="product:availability" content="out of stock" />` and `<meta property="og:availability" content="out of stock" />`

### When a product is out of stock but is set to allow back ordering
- Alter the value of `product:availability` from `in stock` to `available for order`.

  E.g., `<meta property="product:availability" content="available for order" />`

-  Alter the `availability` property of the schema `Offer` from `http://schema.org/InStock` to `https://schema.org/PreOrder`.

-  Add a `og:availability` meta tag with a value of backorder.
  E.g., `<meta property="og:availability" content="backorder" />`

**Comment by afercia** [comment]
To clarify: 

> When a product is in stock
> Output a og:availability meta tag.

I read this as we should output _only_ the `og:availability` meta tag.

> When a product is out of stock but is set to allow back ordering
> Alter the value of product:availability from in stock to available for order.

Instead, this sounds like a `product:availability` > `in stock` is there.

I'm assuming we should output both, correct?

**Comment by jono-alderson** [comment]
Yep. These requirements should be read as 'in addition to current behaviour', except for where instructions alter existing behaviour.

**Comment by igorschoester** [comment]
Please note the output of all this got changed to presenters for the indexables in the upcoming 13.0 release in #568
