### ISSUE TITLE
Merge indexables branch to trunk and create RC for 13.0

### ISSUE THREAD

**Issue by johannadevos** [Yoast/wpseo-woocommerce#564]
- [x] Set minimal version for Yoast SEO to 14.0
- [x] Merge `feature/indexables-frontend` to `trunk`
- [x] Create `release/13.0` from `trunk`
- [x] Create 13.0-RC1

**Comment by hansjovis** [comment]
13.0-RC1 has been created: https://github.com/Yoast/wpseo-woocommerce/releases/tag/13.0-RC1
