### ISSUE TITLE
Adds logic to bring back the og metatags #802

### ISSUE THREAD

**Issue by andizer** [Yoast/wpseo-woocommerce#566]
With the upcoming release of Yoast SEO 14.0 the filter wpseo_opengraph is deprecated. Woocommerce SEO is hooking into this filter for rendering OG metatags. We should replaces these by presenters.

For reference see:
https://github.com/Yoast/wpseo-woocommerce/blob/c0ea263345da47cb3b58c3855a5f03ee3cf5b0da/classes/woocommerce-opengraph.php#L21

https://github.com/Yoast/wpseo-woocommerce/blob/c0ea263345da47cb3b58c3855a5f03ee3cf5b0da/classes/woocommerce-opengraph.php#L72

**Comment by hansjovis** [comment]
Fixed in https://github.com/Yoast/wpseo-woocommerce/pull/568.
