### ISSUE TITLE
Create tests for the product presenters

### ISSUE THREAD

**Issue by igorschoester** [Yoast/wpseo-woocommerce#577]
See implementation PR https://github.com/Yoast/wpseo-woocommerce/pull/568

There are tests missing for the presenters.

I just started with the brand presenter, so here is that in a text file (note the extension).
[product-brand-presenter-test.php.txt](https://github.com/Yoast/wpseo-woocommerce/files/4443022/product-brand-presenter-test.php.txt)

**Comment by hansjovis** [comment]
Fixed in https://github.com/Yoast/wpseo-woocommerce/pull/593.
