### ISSUE TITLE
Product meta incorrectly output on category pages

### ISSUE THREAD

**Issue by jono-alderson** [Yoast/wpseo-woocommerce#580]
On product pages, we output a series of meta tags describing a product's price, availability, and other properties.

E.g.,
```
<meta property="product:price:amount" content="20.00" />
<meta property="product:price:currency" content="GBP" />
<meta property="og:availability" content="instock" />
<meta property="product:availability" content="in stock" />
<meta property="product:retailer_item_id" content="woo-polo" />
<meta property="product:condition" content="new" />
```

However, these tags are also output on category pages. Curiously, it looks as if the tags output on the category page don't necessarily reflect any of the products in that category. Regardless, they should be removed/disabled.

Tested with:
`Yoast SEO (beta) | release/14.0 | 08-04-2020 09:45`
`Yoast SEO: WooCommerce | 12.7`
`WooCommerce | 4.0.1`

**Comment by dariaknl** [comment]
@jono-alderson can you try to reproduce it on SEO Woocommerce version 13.0 RC2 (shared in test channel)?

**Comment by jdevalk** [comment]
Cannot reproduce on release branch.
