### ISSUE TITLE
og:description always falls back to content if not empty

### ISSUE THREAD

**Issue by dariaknl** [Yoast/wpseo-woocommerce#581]
### How can we reproduce this behavior?
1. Install and activate Yoast SEO 14.0 RC4.
2. Install and activate Woocommerce 4.0.1.
3. Install and activate SEO Woo 13.0 RC2.
4. Make sure you  have configured template for product categories:
<img width="654" alt="Screenshot 2020-04-13 at 09 05 53" src="https://user-images.githubusercontent.com/19681708/79100144-ff807900-7d65-11ea-8118-911eafbeb0aa.png">

5. Start creating new product category with empty content, see that default template is applied:
<img width="428" alt="Screenshot 2020-04-13 at 09 08 15" src="https://user-images.githubusercontent.com/19681708/79100239-52f2c700-7d66-11ea-8b58-7d249e6e93a7.png">

6. Publish category and check description tags:

```
<meta name="description" content="default" />
<meta property="og:description" content="default" />
```

7. Add content to category, word "content", update category.
8. Check description tags:

```
<meta name="description" content="default" />
<meta property="og:description" content="content" />
```

It is expected that `og:description` stays `default`. 

The issue is reproduced in SEO Woo 12.9 as well, `og:description` always falls back to content of category (even when user-defined meta description (or template) is configured). But we have designed now in 14.0 [unified fallback behaviour](https://developer.yoast.com/features/meta-tags/), so I would expect this to be fixed. The same is reproduced for product tags.

### Technical info
* WordPress version: 5.4
* Yoast SEO version: 14.0 RC4
* Yoast SEO for WooCommerce version: 13.0 RC2

**Comment by johannadevos** [comment]
Fixed in #592
