### ISSUE TITLE
Deprecation warnings for all products

### ISSUE THREAD

**Issue by dariaknl** [Yoast/wpseo-woocommerce#582]
### How can we reproduce this behavior?
1. Install and activate Yoast SEO 14.0 RC4.
2. Install and activate Woocommerce 4.0.1.
3. Install and activate SEO Woo 13.0 RC2.
4. Configure Knowledge graph with Organisation and logo.
5. Create new empty product, add only price.
6. Publish product and browse to it:
<img width="743" alt="Screenshot 2020-04-13 at 10 01 54" src="https://user-images.githubusercontent.com/19681708/79103938-d49a2300-7d6d-11ea-847d-bf8ba291b518.png">

```
Deprecated: WPSEO_Schema_Image::__construct is deprecated since version WPSEO 14.0! Use YoastSEO()->helpers->schema->image instead. in /srv/www/local/public_html/wp-includes/functions.php on line 4713

Deprecated: WPSEO_Schema_Image::generate_from_url is deprecated since version WPSEO 14.0! Use YoastSEO()->helpers->schema->image->generate_from_url instead. in /srv/www/local/public_html/wp-includes/functions.php on line 4713
```
Warnings are shown for all existing products, not only newly created.

I am not expecting any warnings, however it is mentioned [here](https://github.com/Yoast/wpseo-woocommerce/pull/568) that deprecation warning will be shown but only when functions are still called by external parties. In this case I only have Woocommerce itself.

### Technical info
* WordPress version: 5.4
* Yoast SEO version: 14.0 RC4
* Yoast SEO for WooCommerce version: 13.0 RC2

**Comment by andizer** [comment]
Is fixed in #588
