### ISSUE TITLE
"article:publisher" output for products

### ISSUE THREAD

**Issue by dariaknl** [Yoast/wpseo-woocommerce#583]
### How can we reproduce this behavior?

1. How can we reproduce this behavior?
2. Install and activate Yoast SEO 14.0 RC4.
3. Install and activate Woocommerce 4.0.1. 
4. Install and activate SEO Woo 13.0 RC2.
4. Configure Knowledge graph with Organisation and logo.
5. Fill in Facebook url in SEO - Social.
6. Create new empty product, add only price.
7. Publish it and browse to products, check tags:
you get among the tags 
```meta property="article:publisher" content="https://www.facebook.com/yoast">```

In Yoast SEO 13.5 RC + Woocommerce + SEO Woo 12.7 `article:publisher` was not output for products. I have not found in our docs that was done intended.

### Technical info
* WordPress version: 5.4
* Yoast SEO version: 14.0 RC4
* SEO Woo 13.0 RC2.

**Comment by andizer** [comment]
Is fixed in #588
