### ISSUE TITLE
"article:modified_time" output for products

### ISSUE THREAD

**Issue by dariaknl** [Yoast/wpseo-woocommerce#584]
### How can we reproduce this behavior?

1. How can we reproduce this behavior?
2. Install and activate Yoast SEO 14.0 RC4.
3. Install and activate Woocommerce 4.0.1. 
4. Install and activate SEO Woo 13.0 RC2.
5. Create new empty product.
6. Publish it.
7. Go to edit your new product, add price.
8 Browse to product, check tags:
you get `property="article:modified_time"`

In the following currect combanations:
* Yoast SEO 13.5 RC + Woocommerce 
or
* Yoast SEO 13.5 RC + Woocommerce + SEO Woo 12.7 
`article:modified_time` was never output.

### Technical info
* WordPress version: 5.4
* Yoast SEO version: 14.0 RC4
* SEO Woo 13.0 RC2.

**Comment by dariaknl** [comment]
this issue seems the same as https://github.com/Yoast/wpseo-woocommerce/issues/583

**Comment by jdevalk** [comment]
Decided to keep this one, as Google uses it too.
