### ISSUE TITLE
Multiple "og:image" misalignment

### ISSUE THREAD

**Issue by dariaknl** [Yoast/wpseo-woocommerce#585]
### How can we reproduce this behavior?

1. How can we reproduce this behavior?
2. Install and activate Yoast SEO 14.0 RC4.
3. Install and activate Woocommerce 4.0.1. 
4. Install and activate SEO Woo 13.0 RC2.
5. Create new product, add price and 2 image in Product gallery
6. Publish it and check` og:image` tags:

You get for og:
```
<meta property="og:image" content="http://local.wordpress.test/wp-content/uploads/elmo.jpg" />
<meta property="og:image:width" content="246" />
<meta property="og:image:height" content="246" /><meta property="og:image" content="http://local.wordpress.test/wp-content/uploads/cookie-monster-1116.png" />
<meta property="og:image:width" content="570" />
<meta property="og:image:height" content="570" />
```

It is expected to get:
```
<meta property="og:image" content="http://local.wordpress.test/wp-content/uploads/elmo.jpg" />
<meta property="og:image:width" content="246" />
<meta property="og:image:height" content="246" />
<meta property="og:image" content="http://local.wordpress.test/wp-content/uploads/cookie-monster-1116.png" />
<meta property="og:image:width" content="570" />
<meta property="og:image:height" content="570" />
```

### Technical info
* WordPress version: 5.4
* Yoast SEO version: 14.0 RC4
* SEO Woo 13.0 RC2.

**Comment by jdevalk** [comment]
Not really an issue in `wpseo-woocommerce`, more in core Yoast SEO. Also, the alignment really doesn't matter all that much :)
