### ISSUE TITLE
Product tags output still different from current SEO Woo version

### ISSUE THREAD

**Issue by dariaknl** [Yoast/wpseo-woocommerce#586]
### How can we reproduce this behavior?

While testing this https://github.com/Yoast/wpseo-woocommerce/pull/568 by executing steps from fixed issue https://github.com/Yoast/bugreports/issues/950 the following has been found.

Execute:
1. Install and activate Yoast SEO 14.0 RC4.
2. Install and activate Woocommerce 4.0.1. 
3. Install and activate SEO Woo 13.0 RC2.
4. Set Product Brand 
<img width="652" alt="Screenshot 2020-04-13 at 11 33 16" src="https://user-images.githubusercontent.com/19681708/79110495-d5858180-7d7a-11ea-8834-88b199bc7804.png">

5. Create new product setting price and allocating Product Tag so you get Brand output.
6. Publish product and browse to it:

<img width="888" alt="Screenshot 2020-04-13 at 11 36 27" src="https://user-images.githubusercontent.com/19681708/79110570-0a91d400-7d7b-11ea-919b-fa380b085849.png">

Result:

1. All product tags are output after schema json. In Yoast SEO 13.5 + Woo SEO 12.78 it is json tag os the last one in the output.
2. `product:retailer_item_id` is still missing.

### Technical info
* WordPress version: 5.4
* Yoast SEO version: 14.0 RC4
* SEO Woo 13.0 RC2.

**Comment by jdevalk** [comment]
1. is not a problem.
2. is a problem though and needs fixing.

**Comment by andizer** [comment]
Is fixed in #588
