### ISSUE TITLE
Page not found for sitemaps product, product_tag, product_cat, and product_shipping_class

### ISSUE THREAD

**Issue by CarolineGeven** [Yoast/wpseo-woocommerce#60]
When there are no products yet, the product-sitemap.xml shows a page not found.

 When there are products, but they do not have tags, categories or a shipping_class, the following sitemaps show a page not found:
- product_tag-sitemap.xml
- product_cat-sitemap.xml
- product_shipping_class-sitemap.xml

Ideally we do not want to show these sitemaps at all if they do not contain anything.

Probably related to https://github.com/Yoast/wordpress-seo/issues/2172

**Comment by boblinthorst** [comment]
The described issue no longer seems to be present. Closing this.
