### ISSUE TITLE
"Internal Links settings page" link needs to be updated

### ISSUE THREAD

**Issue by monbauza** [Yoast/wpseo-woocommerce#61]
![woocommerce-seo-link](https://cloud.githubusercontent.com/assets/9658774/7083824/a8ee83ea-df66-11e4-9401-a95c5a3e322d.png)

**Comment by monbauza** [comment]
Still the same in WooCommerce SEO 3.0

**Comment by boblinthorst** [comment]
Layout has been changed. Closing this issue.
