### ISSUE TITLE
Possible Issue With Twitter Product Cards

### ISSUE THREAD

**Issue by amboutwe** [Yoast/wpseo-woocommerce#62]
Multiple users with product cards not working as expected. Cards show correctly in the validator but do not appear when sending an actual tweet.

Example product URLs
retronovelties / [Product URL](http://www.retronovelties.com/shop/pee-wee-herman-bobble-head/) / [Tweet URL](https://twitter.com/RetroNovelties/status/598934610727346177)
canvasil / [Product URL](https://canvasil.com/product/zebra-love/) / [Tweet URL](https://twitter.com/canvasil/status/600260337372372994)
airgunproshop / [Product URL](http://www.airgunproshop.com/shop/refurbished-hatsan-125-sniper-camo-177-cal/) / [Tweet URL](https://twitter.com/airgunproshop/status/596427740317810689)

I was able to reproduce this on a dummy site of my own.
http://www.designsbyangi.com/template/shop/test/
https://twitter.com/timcindyn/status/601173139930947584

**Comment by amboutwe** [comment]
Please inform the customer of these conversations when this issue has been closed.

retronovelties - # 59527
canvasil - # 47916
airgunproshop - # 47583

**Comment by Rarst** [comment]
Went through the spec for product cards and nothing jumps out at me as being wrong. As long as validator says everything is fine, there is no starting point what is there to fix (if anything).

**Comment by amboutwe** [comment]
Thanks @Rarst for checking as I didn't find anything that stood out either. I see that a handful of other Twitter users are having similar issues, specifically with product cards. I wonder if something has changed on Twitter's end. I'll monitor the [Twitter forum report](https://twittercommunity.com/t/twitter-cards-not-working-details-link-missing/37873) and update if I learn something has changed.

**Comment by amboutwe** [comment]
Twitter "fixed" something on their end and product cards are working again.
