### ISSUE TITLE
Conflict with WooCommerce Advanced Ajax Layered Navigation

### ISSUE THREAD

**Issue by amboutwe** [Yoast/wpseo-woocommerce#63]
When WooCommerce SEO is activated the WooCommerce filters can't be removed. Occurs when WooCommerce SEO, WooCommerce, and WooCommerce Advanced Ajax Layered Navigation are only the only active plugins. After disabling WooCommerce SEO, the filters remove as expected.

Current outcome: Attribute remains selected.
Expected outcome: Attribute would be removed or reset.

**Versions**
WP version: 4.2.2
WP SEO 2.1.1
WooCommerce SEO 1.1.6
WooCommerce 2.3.10
WooCommerce Advanced Ajax Layered Navigation 1.3.9

**Steps To Reproduce with screenshots**
1. Click on boutique. [{screenshot}](https://d33v4339jhl8k0.cloudfront.net/inline/2165/e138b81550ccec6a45ad59f696f7eb9997cc67e7/ae8f054209f742907b8bd70e8cc5ec89f41a2012/Unknown.png)
2. Enter "zoeva" in search [{screenshot}](https://d33v4339jhl8k0.cloudfront.net/inline/2165/0a33c47c8f0ce8399960c5a4a072051dc49a0e44/8581c46ba5e1ef21b885723c2a8675d3585ec1c7/Unknown.png)
3. Select an attribute like "Ombres à paupières" [{screenshot}](https://d33v4339jhl8k0.cloudfront.net/inline/2165/f104bdcbd4d57081ed01b005bc877e8cc4b07a6c/53fbe763226f212057cba4c3f9c7ef3a8152b8bd/Unknown.png)
4. Click the X to remove the attribute. [{screenshot}](https://d33v4339jhl8k0.cloudfront.net/inline/2165/8cc6da905e66f6ba3cb0be16606ad72589f5138f/9494d4a72a9dbe131f33fe67b2d3883199f6052f/Unknown.png)

**Comment by amboutwe** [comment]
Please inform the customer of conversation # 61200 when this issue has been closed.

**Comment by michelkusters** [comment]
+1

**Comment by monbauza** [comment]
Please inform the customer of conversation # 87680 when this issue has been closed.

**Comment by mlbanddrb** [comment]
Please inform the customer of conversation # 102736 when this issue has been closed.

**Comment by martijnvaneeghem** [comment]
As the last comment is from 2016, please create a new issue (bugreport) if it should still be relevant.
