### ISSUE TITLE
Conflict with WooCommerce Layered Navigation Widget

### ISSUE THREAD

**Issue by amboutwe** [Yoast/wpseo-woocommerce#64]
Possible conflict between WooCommerce SEO and the WooCommerce Layered Nav Widget. WooCommerce filters can't be reset or removed when WooCommerce SEO is activate.

Current outcome: Attribute remains selected.
Expected outcome: Attribute would be removed or reset.

**Versions**
WP version: 4.2.2
WooCommerce SEO 1.1.6
WP SEO 2.2.1
WooCommerce 2.3.10

**Steps To Reproduce**
Same as #63 so possibly related issue

**Comment by amboutwe** [comment]
Please inform the customer of conversation # 61180 when this issue has been closed.

**Comment by AskKim** [comment]
Please inform the customer of conversation # 73870 when this issue has been closed.

**Comment by michelkusters** [comment]
Same problem here.

It works on category archive pages.
But the problem exists on shop page and product search results page.

WordPress 4.3.1
WooCommerce 2.4.10
Yoast WooCommerce SEO 3.0

**Comment by monbauza** [comment]
Please inform the customer of conversation # 87680 when this issue has been closed.

**Comment by Crob0** [comment]
+1

**Comment by mlbanddrb** [comment]
Please inform the customer of conversation # 102736 when this issue has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 104611 when this issue has been closed.

**Comment by thomasandersen** [comment]
+1

**Comment by martijnvaneeghem** [comment]
As the last comment is from 2016, please create a new issue (bugreport) if it should still be relevant.
