### ISSUE TITLE
Remove deprecated methods (2021 cleanup) 

### ISSUE THREAD

**Issue by JoseeWouters** [Yoast/wpseo-woocommerce#664]
All deprecated functions that were deprecated before version 12.5 should be removed.

All deprecated methods in the plugin have something like: `@deprecated [version number]`

Last year's issue: [14175](https://github.com/Yoast/wordpress-seo/issues/14175)

**Comment by johannadevos** [comment]
Closing this issue, a quick search by @andizer showed that there is nothing to deprecate in the past year.
