### ISSUE TITLE
WPSEO_Utils::schema_output and WPSEO_Utils::schema_tag are deprecated since WPSEO 15.5

### ISSUE THREAD

**Issue by CJ42** [Yoast/wpseo-woocommerce#668]
### What did you expect to happen?

No warning messages.

### What happened instead?

Warning shown on single product page and `debug.log` file with `WP_DEBUG` and `WP_DEBUG_LOG` set to **true**

Here is the following warning message:

```
[12-Mar-2021 16:28:13 UTC] PHP Deprecated:  WPSEO_Utils::schema_output is <strong>deprecated</strong> since version WPSEO 15.5 with no alternative available. in /home/customer/www/yourdomain/public_html/wp-includes/functions.php on line 4871

[12-Mar-2021 16:28:13 UTC] PHP Deprecated:  WPSEO_Utils::schema_tag is <strong>deprecated</strong> since version WPSEO 15.5 with no alternative available. in /home/customer/www/yourdomain/public_html/wp-includes/functions.php on line 4871
```

### How can we reproduce this behavior?

Have a basic Wordpress installation ready, with the following constants in `wp-config.php`:

```php
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
```
  
1. Downloads and install the minimum required plugins: Woocommerce, Yoast SEO and Yoast SEO WooCommerce
     1.1 Create a sample product
2. Check for Plugin Conflicts,
     2.1 using the tutorial in yoast.com: https://yoast.com/help/how-to-check-for-plugin-conflicts/
     2.2 **Stop at point 7 (included)**
3. Go to Plugins > Installed Plugins and _Enable while troubleshooting_ for Woocommerce and Yoast SEO plugins.

4. Go to the product page of the sample product created and refresh the page
     4.1 Check the front end and in`wp-content/debug.log`
     4.2 No message should appear

5. Go back to Plugins > Installed Plugins and __Enable while troubleshooting__ for Yoast SEO: WooCommerce plugin

6. Go to the product page of the sample product created and refresh the page
     6.1 Check the front end and in`wp-content/debug.log`
     6.2 The warning message above should appear

### Technical info
* WordPress version: 5.7
* Yoast SEO version: 15.9.2
* Yoast SEO for WooCommerce version: 13.7

**Comment by Djennez** [comment]
You should probably update to the latest version of WooCommerce SEO (13.9 as of the moment of writing). The latest version does not use these deprecated methods. If updating doesn't fix this for you, there's other code in your site that is calling these methods.

**Comment by CJ42** [comment]
Thank you, that fixed the issue.
