### ISSUE TITLE
Support for Woocommerce Endpoints

### ISSUE THREAD

**Issue by Dooza** [Yoast/wpseo-woocommerce#67]
Wordpress SEO doesn't have a way to set titles for Woocommerce pages with endpoints. I can do this fairly easily via wpseo_title but it would be good to have support in the plugin.

Also, it would be good if the breadcrumbs could support endpoints too. For instance, when viewing an order I have Home | My Account as the breadcrumbs, but My Account isn't a link. It would be good to have Home | My Account | View Order #18723 as the breadcrumb. I know its not this plugin, but thought I would mention it as it is related.

**Comment by BenRacicot** [comment]
+1 I can second this issue. There seems to be no way to easily add meta to the endpoint pages.

**Comment by tommyredz91** [comment]
My WC account endpoints are not properly redirecting, so the customer won't either bè able to access and modify any of the input fields on the account page. I have got the AccessPress Mag free theme set-up on my site at: http://floodnews.net.
What on Earth am I supposed to do, to make it work properly once and for all?!?
Tell me how to fix this major issue once and for all, step by step, in detail!!

**Comment by moorscode** [comment]
This is possible in the latest versions of Yoast SEO, WooCommerce and WooCommerce SEO.
