### ISSUE TITLE
Is not compatible with PHP 8

### ISSUE THREAD

**Issue by LeGiangAnh** [Yoast/wpseo-woocommerce#673]
`Fatal error: Uncaught TypeError: Cannot access offset of type string on string in /home/outlet.ltd/public_html/wp-content/plugins/wpseo-woocommerce/classes/woocommerce-schema.php:535 Stack trace: #0 /home/outlet.ltd/public_html/wp-content/plugins/wpseo-woocommerce/classes/woocommerce-schema.php(163): WPSEO_WooCommerce_Schema->filter_reviews() #1 /home/outlet.ltd/public_html/wp-includes/class-wp-hook.php(292): WPSEO_WooCommerce_Schema->change_product() #2 /home/outlet.ltd/public_html/wp-includes/plugin.php(212): WP_Hook->apply_filters() #3 /home/outlet.ltd/public_html/wp-content/plugins/woocommerce/includes/class-wc-structured-data.php(328): apply_filters() #4 /home/outlet.ltd/public_html/wp-includes/class-wp-hook.php(292): WC_Structured_Data->generate_product_data() #5 /home/outlet.ltd/public_html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters() #6 /home/outlet.ltd/public_html/wp-includes/plugin.php(484): WP_Hook->do_action() #7 /home/outlet.ltd/public_html/wp-content/themes/rehub-theme/inc/product_layout/sections_w_sidebar.php(195): do_action() #8 /home/outlet.ltd/public_html/wp-content/themes/rehub-theme/woocommerce/single-product.php(80): include('...') #9 /home/outlet.ltd/public_html/wp-includes/template-loader.php(106): include('...') #10 /home/outlet.ltd/public_html/wp-blog-header.php(19): require_once('...') #11 /home/outlet.ltd/public_html/index.php(17): require('...') #12 {main} thrown in /home/outlet.ltd/public_html/wp-content/plugins/wpseo-woocommerce/classes/woocommerce-schema.php on line 535`
There has been a critical error on this website.

**Comment by Djennez** [comment]
@LeGiangAnh can you please submit additional details as to how to reproduce this issue. I am running the plugin on PHP8 and I am not running into any errors. Your log points to a file which code also runs without issue for me. So at the moemnt, this seems like a site-specific issue.

**Comment by LeGiangAnh** [comment]
> @LeGiangAnh can you please submit additional details as to how to reproduce this issue. I am running the plugin on PHP8 and I am not running into any errors. Your log points to a file which code also runs without issue for me. So at the moemnt, this seems like a site-specific issue.

Please check this link https://outlet.ltd/product/encharge/

**Comment by Djennez** [comment]
What am I looking for on that page?

**Comment by LeGiangAnh** [comment]
![image](https://user-images.githubusercontent.com/5027251/113274965-75c81380-9308-11eb-89e0-2b2bffd3b758.png)

**Comment by Djennez** [comment]
Those are different messages to the one you initially reported. And there are still no reproduction steps to get to any of these results.

**Comment by LeGiangAnh** [comment]
Reproduce steps:

- Install the plugin on PHP 8.0.2, Litespeed server
- See the errors

**Comment by Djennez** [comment]
We use GitHub exclusively for well-documented bug reports or feature requests. This is not a support forum for questions and case-specific support. To receive free support for Yoast SEO we have the following channels:
- [Yoast Knowledge base](http://kb.yoast.com/)
- [Support forums](https://wordpress.org/support/plugin/wordpress-seo) on WordPress.org

If you are a premium customer, you may also contact our team of support engineers directly via e-mail.

Your issue unfortunately does not contain enough information to be a viable bug report or feature request. If you feel like your bug or enhancement is a valid one and should be reviewed by us, then please use the provided templates, read our [contribution guidelines](https://github.com/Yoast/wordpress-seo/blob/trunk/.github/CONTRIBUTING.md) and submit a new issue.

Thank you for your understanding.
