### ISSUE TITLE
Change Twitter Card workings

### ISSUE THREAD

**Issue by jdevalk** [Yoast/wpseo-woocommerce#68]
I don't know why we missed this, nor where to find a link announcing this change, but apparently, the Twitter product card [has been deprecated](https://dev.twitter.com/cards/types/product). We should change the code relating to this from WooCommerce SEO and instead make it output a good text about the product in a summary card.

**Comment by AskKim** [comment]
Please let customer in # 76023 know when this is solved.

**Comment by AskKim** [comment]
Product cards are now coming up as invalid type in the validator and we are probably now facing a bug rather than an enhancement. https://dev.twitter.com/docs/cards/validation/validator

**Comment by Rarst** [comment]
What does WC plugin do on top of SEO for this? I had removed deprecated cards (including product) there in https://github.com/Yoast/wordpress-seo/pull/2927

**Comment by AskKim** [comment]
Looking at that other thread, it appears that you did/started the inclusion of Summary cards. I think that's probably the goal. For Summary to replace Product cards. Customer in 76023 indicated Summary cards were not working due to missing data.
