### ISSUE TITLE
Empty Product Feed URL

### ISSUE THREAD

**Issue by amboutwe** [Yoast/wpseo-woocommerce#69]
The activation of WooCommerce SEO breaks the product feed

[Screenshot](http://www.evernote.com/shard/s198/sh/9dd60341-6b9e-45d3-944d-0e046b33afa4/8716dece8e5711b3d61f8394c54fa1e3)

**Versions**
WP 4.2.2
Yoast SEO 2.3.1
WooCommerce SEO 1.1.6
WooCommerce 2.3.13

Replicated on Yoast support site

**Comment by amboutwe** [comment]
Please inform the customer of conversation # 66184 when this issue has been closed.

**Comment by WendyMerritt** [comment]
Yep! Same problem here. If the plugin in activated there is a blank in the code. If the plugin is deactivated the code/URL shows up but the feed is still empty. Very frustrating.

**Comment by boblinthorst** [comment]
Checked with the most recent version. Seemed to work. link to feed was present. Closing this issue.
