### ISSUE TITLE
Update reference to Yoast SEO

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/wpseo-woocommerce#70]
In [version 2.3 of Yoast SEO](https://yoast.com/yoast-seo-2-3/) we've changed the name of the plugin from WordPress SEO by Yoast to Yoast SEO. We've also handled plugin naming slightly different in translatable strings, as you can [see in this PR](https://github.com/Yoast/wordpress-seo/pull/2612/files).

To match those changes, WooCommerce SEO needs a little updating as well. 

**To do**
- [x] Change WordPress SEO (by Yoast) to Yoast SEO
- [x] sprintf plugin name in translatable strings (see [here](https://github.com/Yoast/wordpress-seo/pull/2612/files#diff-5760ab75dd09613c40985f1c542620a1R200))

**Comment by omarreiss** [comment]
As far as I can see, this is correct everywhere.
