### ISSUE TITLE
Readability Error in Products

### ISSUE THREAD

**Issue by iamheretoscale** [Yoast/wpseo-woocommerce#729]
### What did you expect to happen?
**"Subheading distribution"** and **"Paragraph length"** display correct improvements.

### What happened instead?
Count of numbers is wrong and display Zero "0". for example in any condition I've got this errors:

_Subheading distribution: 0 sections of your text are longer than 300 words and are not separated by any subheadings. Add subheadings to improve readability._

_Paragraph length: 0 of the paragraphs contain more than the recommended maximum of 70 words. Shorten your paragraphs!_

**"0 sections"** and **"0 of the paragraphs"**

### How can we reproduce this behavior?

1. install latest wordpress.
2. install latest yoast seo Free
3. install latest yoast seo premium
4. Install latest Woocommerce plugin
5. Add new Product
6. fill Sample Description with minimum two subheadings and long sentences.
7. Check **"Subheading distribution"** and **"Paragraph length"** in Readability Tab.

![image_2021-12-01_222400](https://user-images.githubusercontent.com/26019907/144295984-b193615e-2583-4436-8c41-8603777f3c60.png)

### Technical info
* WordPress version: 5.8
* Yoast SEO version: 17.7
* Yoast SEO for WooCommerce version: 14.4

**Comment by Djennez** [comment]
@amirassari2002 this is working correctly on a local test installation. You might have a plugin conflict or another problem. Since you indicate to use our Premium plugin, please contact our support directly to investigate this, as this is not a valid bugreport for GitHub here.

**Comment by amirassari2002** [comment]
Hi @Djennez 
i had tested it on sandbox again.
you can check it yourself on sandbox 

Admin area URL: https://slidetoad.tastewp.com/wp-admin
Username: admin
Password: 07mh3FWtkCo


**Yoast seo free version** and **wpseo-woocommerce 14.4**

problem exist. (only you must check Product post type)

how did you check at your side?

sample text to see errors: (input on wordpress default editor)

`Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas purus viverra accumsan in nisl nisi. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. In egestas erat imperdiet sed euismod nisi porta lorem mollis. Morbi tristique senectus et netus.

test

Mattis pellentesque id nibh tortor id aliquet lectus proin. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Dictum varius duis at consectetur lorem. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Velit ut tortor pretium viverra suspendisse potenti nullam. Et Mattis pellentesque id nibh tortor id aliquet lectus proin. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Dictum varius duis at consectetur lorem. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Velit ut tortor pretium viverra suspendisse potenti nullam. Et Mattis pellentesque id nibh tortor id aliquet lectus proin. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Dictum varius duis at consectetur lorem. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Velit ut tortor pretium viverra suspendisse potenti nullam. Et Mattis pellentesque id nibh tortor id aliquet lectus proin. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Dictum varius duis at consectetur lorem. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Velit ut tortor pretium viverra suspendisse potenti nullam. Et Mattis pellentesque id nibh tortor id aliquet lectus proin. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Dictum varius duis at consectetur lorem. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Velit ut tortor pretium viverra suspendisse potenti nullam. Et `

**Comment by suascat** [comment]
https://yoast.atlassian.net/browse/IM-1636
