### ISSUE TITLE
Include Product Short Description in page analysis

### ISSUE THREAD

**Issue by tacoverdo** [Yoast/wpseo-woocommerce#73]
**Steps to reproduce**
Create a new product with the following details.
Title: `very expensive tomato`
Content: 

```
Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui.

Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero. Fusce vulputate eleifend sapien. Vestibulum purus quam, scelerisque ut, mollis sed, nonummy id, metus. Nullam accumsan lorem in dui. Cras ultricies mi eu turpis hendrerit fringilla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In ac dui quis mi consectetuer lacinia.

This is the long description of my expensive product.
```

Product Short Description: `This is the short description of my expensive product. It contains my keyword: tomato.`

Focus keyword in Yoast SEO: `tomato`
Resulting analysis: 
![edit_product_ _clean_ _wordpress](https://cloud.githubusercontent.com/assets/5147598/10139210/206427b4-6602-11e5-8b55-797e9e9639bb.png)

**Problem description**
Since the focus keyword (tomato) is in the Product Short Description, one would guess it'd be taken into account in the analysis. This unfortunately does not seem to be the case. 

**Possible solution**
Add the Product Short Description to the analysis.

**Versions**
WordPress 4.3.1
Yoast SEO for WordPress 2.3.5
WooCommerce 2.4.7
WooCommerce SEO 1.1.6

**Comment by AskKim** [comment]
User from ticket # 76006 provides this additional information: 

Katie Tidey replied

Dear Kimberley

Thanks for your honesty.

It seems that your Yoast WooCommerce SEO does detect some content in the Short Description box but this is only identified as 'body copy' if I select the 'Page Analysis' option in 'Yoast SEO' - It does not identify this as 'content' under the Yoast SEO 'General' tab. I would have thought all info in the Short Description box is page content as well so should turn the content indicator to 'Green' and 'Yes' but it doesnt.

FYI - If its of any help I am using the Woothemes Shortcode Tab Layout function inside the Short Description Box. It seems that Yoast doesnt recognise all the content in each tab so gives a very poor score for 'body copy'. It states:

'There are 141 words contained in the body copy. This is below the 200 word recommended minimum. Add more useful content on this topic for readers.'

However I have many more words than this its just that they are in a tabbed layout and Yoast isnt recognising this.

Unfortunately Yoast then contradicts itself and states:

'The short description for this product is too long.'

Its obviously not recognising that I have chosen to use the Short Description box for my main content as opposed to the box at the top of the Edit Product page under the Add Media title.

I have not read any warnings from Woocommerce that there is a limit to the amount of data I can enter in the Short Description box and surely if it displays correctly and offers the viewer all the information necessary then Yoast should recognise this as 'content' and 'body copy'. I have four tabs in my Short Description box and the word count is 2385 across all four tabs not 141.

Yoast also states:

'The keyword doesn't appear in the first paragraph of the copy, make sure the topic is clear immediately.'

However my keyword is in the first line of the first paragraph in the Short Description which is at the top of the page and very visable - Yoast should identify that the keyword is in the Short Description but it isnt recognising this.

I hope the above helps.

Please let me know when you have a fix and roughly and how long you think this will take.

Thank you
Kind Regards
Katie

**Comment by AskKim** [comment]
Please let user in ticket # 76006 know when this is closed.

**Comment by tacoverdo** [comment]
Please inform the customer of conversation # 114337 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # `114665` when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 117841 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 123308 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 123510 when this conversation has been closed.

**Comment by mazedulislamkhan** [comment]
Please inform the customer of conversation # 128313 when this conversation has been closed.

**Comment by AskKim** [comment]
Please inform the customer of conversation # 129893 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 145013 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 149039 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 172496 when this conversation has been closed.

**Comment by tcrgar** [comment]
Hi, is this still an issue? Maybe this request is included in Yoast premium plugin?

**Comment by WalentinWidgren** [comment]
Is this fixed yet?

**Comment by iamazik** [comment]
Please inform the customer of conversation # 222891 when this conversation has been closed.

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 413258 when this conversation has been closed.

**Comment by mariusghitulescu** [comment]
Please inform the customer of conversation # 422721 when this conversation has been closed.

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 437670 when this conversation has been closed.

**Comment by Jerparx** [comment]
Please inform the customer of conversation # 441338 when this conversation has been closed.

**Comment by mayada-ibrahim** [comment]
Please inform the customer of conversation # 448197 when this conversation has been closed.

**Comment by mariusghitulescu** [comment]
Please inform the customer of conversation # 469449 when this conversation has been closed.

**Comment by mayada-ibrahim** [comment]
Please inform the customer of conversation # 477720 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 487520 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 487586 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Yoast checks the short description area for two things. It does not do a fully analysis. 

1. It will output a singular check for length in the short product description area. Specifically, it looks at word count and considers 0 as having no words, 1-19 as short, 20-49 as good, and 50+ as long. 

2. If you added a product gallery the plugin will check it for alt-attributes.

**Comment by mariusghitulescu** [comment]
Please inform the customer of conversation # 502591 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 510091 when this conversation has been closed.

**Comment by iamazik** [comment]
Please inform the customer of conversation # 515750 when this conversation has been closed.

**Comment by LauraYoast** [comment]
Please inform the customer of conversation # 519016 when this conversation has been closed.

**Comment by rmarcano** [comment]
Please inform the customer of conversation # 538571 when this conversation has been closed.

**Comment by bonomabd** [comment]
Please inform the customer of conversation # 502571 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 552300 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 556881 when this conversation has been closed.

**Comment by priscillamc** [comment]
Please inform the customer of conversation # 556995  when this conversation has been closed.
