### ISSUE TITLE
Breadcrumb Consistency

### ISSUE THREAD

**Issue by amboutwe** [Yoast/wpseo-woocommerce#74]
'Taxonomy to show in breadcrumbs for post types' products option does not inherit setting from 'Post type archive to show in breadcrumbs for taxonomies'

**Expected output**

| Level | Breadcrumb |
| --- | --- |
| Shop | Home > Products |
| Product Category | Home > Products > Product Category |
| Product | Home > Products > Product Category > Product Name |

**Current Output**

| Level | Breadcrumb |
| --- | --- |
| Shop | Home > Products |
| Product Category | Home > Products > Product Category |
| Product | Home > Product Category > Product Name |

**Settings to Replicate**
Use Storefront theme

SEO > Advanced > Breadcrumbs - Check enable
![selection_146](https://cloud.githubusercontent.com/assets/8060612/10348903/fa944458-6cf8-11e5-9687-6c4391562c82.png)

SEO > WooSEO - Check replace WooCom breadcrumbs

Add this to functions.php

`// Replace Storefront breadcrumbs With Yoast Breadcrumbs`
`add_action( 'init', 'jk_remove_storefront_breadcrumb' );`
`function jk_remove_storefront_breadcrumb() {`
`remove_action( 'storefront_content_top', 'woocommerce_breadcrumb',     10 );`
`}`
` `
`add_action( 'woocommerce_before_main_content','my_yoast_breadcrumb', 20, 0);`
`if (!function_exists('my_yoast_breadcrumb') ) {`
`   function my_yoast_breadcrumb() {`
`       yoast_breadcrumb('<nav class="woocommerce-breadcrumb">','</nav>');`
`   }`
`}`

**Comment by boblinthorst** [comment]
Checked this issue in the current version. With the correct settings, I was able to have the breadcrumbs behave in the way described as "expected".

Settings were as follows:

**Taxonomy to show in breadcrumbs for post types**
posts > category
Products > product category

**Post type archive to show in breadcrumbs for taxonomies**
Product Category > Products

Closing it for now.
