### ISSUE TITLE
Media grid overview not working on multisite

### ISSUE THREAD

**Issue by diedexx** [Yoast/wpseo-woocommerce#78]
The grid view of the Media overview/library just displays a large white block with no content when the Yoast WooCommerce SEO plugin is activated. The console remains empty as well. 
![screen shot 2015-11-11 at 11 50 58 2](https://cloud.githubusercontent.com/assets/5352634/11089516/aaae6878-886a-11e5-9877-e096b3de6c1c.png)

On the other hand, the List view does work.
![media_library_ _wpmu_subdirectory_trunk_dev_ _wordpress](https://cloud.githubusercontent.com/assets/5352634/11089558/fe4ce130-886a-11e5-92e8-0bc923b87c5c.png)

Using
-
- WordPress 4.3.1 (Multisite - subdirectory)
- Yoast SEO 3.0 beta 11
- Yoast WooCommerce SEO 1.1.6 trunk
- WooCommerce 2.4.10
- Twenty fifteen 1.3

_No other plugins active_

**Comment by omarreiss** [comment]
@diedexx could you test if this has indeed been fixed?

**Comment by diedexx** [comment]
It has been fixed
