### ISSUE TITLE
Add JS filters to replace the removed PHP hooks

### ISSUE THREAD

**Issue by andizer** [Yoast/wpseo-woocommerce#80]
The hooks which are removed in this [pull request](https://github.com/Yoast/wpseo-woocommerce/pull/79) should be replaced by JS hooks

**Comment by omarreiss** [comment]
Context: Product image galleries should be taken into account in the content analysis.

**Comment by tacoverdo** [comment]
Very hard to test at the moment, so waiting for https://github.com/Yoast/wordpress-seo/pull/3246#issuecomment-157309228 to be fixed before continuing acceptance testing.
