### ISSUE TITLE
"nofollow" to Woocommerce layered nav widget

### ISSUE THREAD

**Issue by poissonplume** [Yoast/wpseo-woocommerce#84]
Hello,

I think your plugin is missing an important feature: add "nofollow" to Woocommerce layered nav widgets.
Actually, Google is trying to index any possible filter link in my shop (www.poissonplume-bijoux.com/shop), using the layered nav widgets in the sidebar.

The url from the widgets are like " http://www.poissonplume-bijoux.com/shop/?filter_creatrice=59", which leads to a page that is the same as my optimized page "http://www.poissonplume-bijoux.com/bijouxfantaisie/attribut/creatrice/azucar/" (but, as I optimized it, I created a SEO text on it). I perfectly understand that the url in the filters have to remain dynamic, as it allows to combine parameters. This is indeed very useful from a client perspective. But, from a SEO perspective, this is really ugly, and leads to duplicate content...

"Can you please add the possibility to add the "nofollow" link on the Woocommerce layered nav widgets in a near future version?
Is there any easy way to achieve this, while waiting for a possible new version?

Many thanks again,
Antoine

**Comment by Djennez** [comment]
This feature request hasn't seen any updates in 4 years. It seems to be for a very specific use-case and it would alter output by another plugin on a code level. Wether the request still holds true, I'm going to close this thread for now since it doesn't seem like anything we're going to create.

**Comment by lkraav** [comment]
I'm not sure what's "specific" about this use case? We discovered the same problem, where bots hammer the site like crazy. This seems like a very general and widespread problem to me, *unless* some sites would build specific content setups for some combinations of attributes ~> now *that* might be a "specific" use case.
