### ISSUE TITLE
Remove Product /product/ base from WooCommerce Product URLs

### ISSUE THREAD

**Issue by AskKim** [Yoast/wpseo-woocommerce#87]
I'm unable to tell if it's a bug or intentional that we don't seem to be able to remove the /product/ base from product URLs. 

The WooCommerce team believes we provide this feature and they link to us: https://docs.woothemes.com/document/removing-product-product-category-or-shop-from-the-urls/

This is probably the source of three or four tickets a month at least that request getting this feature working. 

A client ticket requesting this is # 93091 but there are others as well. 

I spun up a demo site and tested if our SEO -> Advanced -> Permalinks option to remove /category/ from URLs would affect this but it does not seem to do so. 

There are a lot of guides swimming around online that have major codeblocks that may or may not have worked at once time, but it's hard to establish whether this is supposed to be working in our plugin or not. 

A similar question is referenced here: https://github.com/Yoast/wordpress-seo/issues/3523

It seems that many people are now using this https://www.perfectseourl.com/ in order to achieve their goal, but I see little reason our WooCommerce SEO plugin can't accomplish the necessary steps when combined with the redirection manager in our Yoast SEO Premium, with a little work. 

We probably have to use care about letting the users manually hack on the URL as they could break the product feed if they do. 

WordPress 4.4
Yoast SEO Premium 3.0.7
WooCommerce 2.4.12 
WooSEO 3.0

**Comment by AskKim** [comment]
Please inform the customer of conversation # 95402 when this conversation has been closed.

**Comment by AskKim** [comment]
Please inform the customer of conversation # 97337 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 98678 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 108688 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 134020 when this conversation has been closed.

**Comment by monbauza** [comment]
The customer in # 147157 would also like to be able to remove the shop base from the URLs.

For example, remove _/shop/_ from _domain/shop/prod-cat/prod_

**Comment by monbauza** [comment]
Please inform the customer of conversation # 147157 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 183612 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 189093 when this conversation has been closed.

**Comment by monbauza** [comment]
Please inform the customer of conversation # 193018 when this conversation has been closed.

**Comment by monbauza** [comment]
It looks like removing the /product-category/ base is not advisable. From the WooCommece document above https://docs.woocommerce.com/document/removing-product-product-category-or-shop-from-the-urls/

> Removing /product/, /product-category/, or /shop/ from the URLs is not advisable due to the way WordPress resolves its URLs. It uses the product-category (or any other text for that matter) base of an URL to detect that it is an URL leading to a product category.

When removing the /product-category/ base
> You will make it harder for WordPress to detect what page you are trying to reach when you type in a product category URL.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 451718 when this conversation has been closed.

**Comment by Pcosta88** [comment]
Please inform the customer of conversation # 557483 when this conversation has been closed.

**Comment by tacoverdo** [comment]
Closed per Jono's advice:
> There's no real SEO benefit other than 'cleanness', and all of the risks/issues outlined in https://docs.woothemes.com/document/removing-product-product-category-or-shop-from-the-urls/ apply. Thus closing this issue.
