### ISSUE TITLE
Attempt to read property "open_graph_image_source" on bool in woocommerce-opengraph.php

### ISSUE THREAD

**Issue by 37Rb** [Yoast/wpseo-woocommerce#875]
* [X] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened

We're seeing this PHP warning in logs.

```
PHP message: PHP Warning: Attempt to read property "open_graph_image_source" on bool in /www/public/wp-content/plugins/wpseo-woocommerce/classes/woocommerce-opengraph.php on line 131
```

It seems like you need to check the return value here before using it. https://github.com/Yoast/wpseo-woocommerce/blob/trunk/classes/woocommerce-opengraph.php#L129

#### Used versions
* Operating system: Linux
* PHP version: 8.1
* WordPress version: 6.1.1
* WordPress Theme: custom
* Yoast SEO version: 20.0
* Yoast SEO for WooCommerce version: 15.5

**Comment by michaelbriantina** [comment]
Please inform the customer of conversation # 1018548 when this conversation has been closed.

**Comment by 37Rb** [comment]
Tired of seeing this warning many times per day. As a temp workaround I changed

```php
                $indexable            = $indexable_repository->find_by_id_and_type( $product_id, 'post' );

                return $indexable->open_graph_image_source === 'set-by-user';
```

to

```php
                $indexable            = $indexable_repository->find_by_id_and_type( $product_id, 'post' );
                if ( is_bool( $indexable ) ) {
                        return false;
                }

                return $indexable->open_graph_image_source === 'set-by-user';
```

**Comment by midweste** [comment]
Having this issue too with Woocommerce Brand plugin - https://woo.com/products/brands/
I see no reason not to check for a property before trying to use it.  Fills the logs

**Comment by 37Rb** [comment]
I submitted a pull request to check before using the property.

https://github.com/Yoast/wpseo-woocommerce/pull/963
