### ISSUE TITLE
Show plugin-specific assessments in Elementor

### ISSUE THREAD

**Issue by mhkuu** [Yoast/wpseo-woocommerce#876]
Adapted from https://yoast.atlassian.net/browse/IM-1982

**What behavior were you expecting?**
 All the assessments which appear in Classic or Block editor to appear in Elementor too.

**What actually happened?**
- They don’t. 
- For Woo: the Product description assessment, Product identifier, SKU, and Lists assessments disappear when post is opened in Elementor

**How can we reproduce the current behavior?**
- Free version: 19.7.1
- Elementor version: 3.7.7
- For Woo (15.2)
  - Create a new product, add a title
  - Confirm that in the SEO analysis tab you can see Product description, Product identifier, and SKU assessments, (You should write a short description for this product.)
  - Confirm that Lists assessment is shown under Readability analysis
  - Save the product
  - Open product in Elementor
  - Open SEO analysis tab and confirm Product description, Product identifier, and SKU assessments are not there
  - Confirm that Lists assessment is not shown under Readability analysis

**If available: what are the tips for fixing the problem or possible solutions?**

- In `wpseo-woocommerce`, the additional assessments mentioned above are eventually loaded in `js/src/yoastseo-woo-worker.js` script. However, it turns out that this script is not loaded when editing in Elementor.
- It’s possible that in other repositories (Video and Local) we have the same issue.

**Comment by monbauza** [comment]
Related: https://github.com/Yoast/featurerequests/issues/723 The product short description is ignored when editing the product with Elementor. In the classic editor, Yoast SEO (along with WooCommerce SEO) does detect the text added to the `Product short description` field.

![image](https://user-images.githubusercontent.com/9658774/217477760-8b7469d1-bb0d-490d-9840-645dcc6c19b0.png)

**Comment by mhkuu** [comment]
Not sure if that's related. 

Anyway, I'll be splitting this issue into three, one for WooCommerce, one for Local, and one for Video 👍
