### ISSUE TITLE
Add HS Beacon

### ISSUE THREAD

**Issue by omarreiss** [Yoast/wpseo-woocommerce#93]
If premium is not active, woo SEO should add de HS beacon to it's own settings page. If it's easier, the beacon could even be added to all settings pages.

**Comment by atimmer** [comment]
@tacoverdo Could you provide a list of articles you want to show as suggestions to the user when they click the beacon?

There can be max 5 pages. On all the current Yoast SEO pages only 2 or 3 articles are suggested.

**Comment by tacoverdo** [comment]
Please list the following articles:

1. http://kb.yoast.com/article/113-configuration-guide-for-yoast-woocommerce-seo
2. http://kb.yoast.com/article/122-rich-snippets-in-search-results
3. http://kb.yoast.com/article/16-my-sitemap-is-giving-a-404-error-what-should-i-do
