### ISSUE TITLE
Add "Provisioned by WooCommerce" to subscriptions purchased on Woo marketplace

### ISSUE THREAD

**Issue by michaelforty** [Yoast/wpseo-woocommerce#934]
## What is the goal of this issue?
 To add a 'Provisioned by WooCommerce' identifier in HelpScout that will show Support Engineers if a Yoast WooCommerce plugin/bundle was purchased in the Woo marketplace.  Similar to how 'Provisioned by Shopify' shows up in the HS subscription information for Yoast Shopify subscriptions.

## What needs to be done to achieve the goal?
 Develop a way of identifying those subscriptions purchased in Woo marketplace.

## Does the issue still need UX or research?
 No

## If available: what are the tips for fixing the problem or possible solutions?
 Refer to the Shopify integration, perhaps that will help get things started.

## What is the expected result/behavior?
 The 'Provisioned by WooCommerce' text will show in HS for Yoast Woo plugin/bundle subscriptions purchased in the Woo marketplace.

## Should documentation be added or updated for this change? and if so, where?
 Not on the support side, but perhaps on the development side documentation will be helful.

**Comment by mmikhan** [comment]
It's been already addressed in a recent Slack conversation between Raymond and me [here](https://yoast.slack.com/archives/C94K4997X/p1695285123236629?thread_ts=1694167621.326299&cid=C94K4997X).

> Since WordPress.com and Bluehost subscriptions are already showing what you have requested on HelpScout to show the _Provisioned by WooCommerce_ subscriptions on the right sidebar, WooCommerce subscriptions will also be shown in the same way automatically ([confirmation from dev](https://yoast.slack.com/archives/C03PM1QLYMV/p1695220112045149))

That means there's no need to change anything thus, closing the issue.
